### ISSUE TITLE
Undefined method `match?` with version 1.5.0.alpha.17 and ruby 2.3.3

### ISSUE THREAD

**Issue by vthib** [asciidoctor/asciidoctor-pdf#1038]
Using the new release 1.5.0.alpha.17, and with ruby 2.3.3, I have a runtime error on a file that used to be correctly handled in the previous version:

```
/var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:1468:in `convert_listing_or_literal': undefined method `match?' for /&#?[a-z\d]+;|</:Regexp (NoMethodError)
Did you mean?  match
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:128:in `convert'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:71:in `convert'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `block in content'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `map'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `content'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:144:in `convert_content_for_block'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:483:in `convert_section'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:128:in `convert'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:71:in `convert'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `block in content'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `map'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `content'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:144:in `convert_content_for_block'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:483:in `convert_section'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:128:in `convert'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:71:in `convert'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `block in content'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `map'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `content'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:144:in `convert_content_for_block'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:483:in `convert_section'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:128:in `convert'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:71:in `convert'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `block in content'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `map'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `content'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:1108:in `content'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:144:in `convert_content_for_block'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:255:in `convert_document'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/converter.rb:128:in `convert'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:1048:in `convert'
        from /usr/lib/ruby/vendor_ruby/asciidoctor.rb:1507:in `convert'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:86:in `each'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:86:in `invoke!'
        from /usr/bin/asciidoctor:14:in `<main>'
```

As far as I can tell, this is caused by the use of the `match?` method on a regex object, which comes in version 2.4 of Ruby. This seems to come from commit 251decae

Unless I'm mistaken, ruby 2.3 is still supported, so this call should probably be rewritten.

**Comment by mojavelinux** [comment]
You are correct that Ruby 2.3 is supported. And that's backed up by the fact that we run the entire test suite of 100+ tests on Ruby 2.3. See https://travis-ci.org/asciidoctor/asciidoctor-pdf.

The problem you're running into is that the version of Asciidoctor you're using (which provides this compatibility method) is too old. You need to be using at least Asciidoctor 1.5.6, though Asciidoctor 2 is preferred.

**Comment by vthib** [comment]
Indeed, I thought I tested it with an updated version of asciidoctor and it still failed, but I must have made a mistake. I updated asciidoctor and it works fine.
Is there a reason the asciidoctor-pdf gem file specifies a dependency on '>= 1.5.0' and not '>= 1.5.6' then?

**Comment by mojavelinux** [comment]
> Is there a reason the asciidoctor-pdf gem file specifies a dependency on '>= 1.5.0' and not '>= 1.5.6' then?

That's an oversight. We can reasonably support back to 1.5.3. I'm working on adding that support as well as automated verification.

**Comment by mojavelinux** [comment]
I've submitted a PR with the fix and the tests are all passing. If it looks good to you, I'll proceed with merging.

**Comment by vthib** [comment]
I can confirm it solves the issue. Thanks a lot!

**Comment by mojavelinux** [comment]
:+1:
