### ISSUE TITLE
epub creation error

### ISSUE THREAD

**Issue by mahmoudparsian** [asciidoctor/asciidoctor-pdf#1229]
Hello,

Can you please help me on this error:

Thanks,
Mahmoud

make epub
asciidoctor --backend=epub3 --require=asciidoctor-epub3  --destination-dir=_build --out-file=book.epub master.adoc; \

/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate': undefined method `activate' for nil:NilClass (NoMethodError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/options.rb:276:in `block in parse!'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/options.rb:274:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/options.rb:274:in `parse!'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/options.rb:34:in `parse!'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:24:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/bin/asciidoctor:13:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/bin/asciidoctor:13:in `<top (required)>'
	from /usr/local/bin/asciidoctor:22:in `load'
	from /usr/local/bin/asciidoctor:22:in `<main>'
make: *** [_build/book.epub] Error 1

This is my master.adoc

 $ cat master.adoc
:author: Mahmoud Parsian
:author_2: Ph.D. in Computer Science
:revnumber: 1.0
//:revdate: July 4, 2019
//:revremark: First draft
:email:  mahmoud.parsian@yahoo.com
:copyright: Mahmoud Parsian 1.0
:doctype: book
:doctitle: PySpark Algorithms
:producer: Mahmoud Parsian
:creator: Mahmoud Parsian
:description: PySpark Algorithms in Action
:keywords: Spark, PySpark, MapReduce, Asciidoctor, samples, e-book, EPUB3, MOBI
//:front-cover-image: images/pyspark_algorithms.pdf
//:front-cover-image: images/pyspark_algorithms2.pdf
:front-cover-image: images/pyspark_algorithms2.jpg
//:title-logo-image: image:logo.png[Logo,100,100]
:title-logo-image: image:logo_001.png[Logo,300,300]
:lang: en
:toc: left
:toclevels: 2
//:sectnumlevels: 3
:sectnumlevels: 5
:numbered:
:icons: font
:icon-set: fi
:imagesdir: {docdir}/images
:source-language: python
:source-highlighter: pygments
:pygments-style: manni
:codedir: {docdir}/code
:datadir: {docdir}/data
:experimental:
:stem: latexmath
//:stem:
:hide-uri-scheme:
:chapter-label: Chapter
:appendix-caption: Appendix
:plantuml-config: {docdir}/_conf/umlconfig.txt
//:font_size: 10

ifdef::backend-html5[]
:data-uri:
:mathematical-format: svg
:mathematical-ppi: 300
endif::[]

ifdef::backend-pdf[]

// shows the actual URL
// :media: prepress

// hide the actual URL
// :media: print

:pdf-stylesdir: _resources/pdfstyles
:pdf-style: default
:mathematical-format: png
endif::[]

ifdef::backend-epub3[]
:imagesdir: images
:epub3-stylesdir: _resources/epubstyles
:ebook-validate:
:mathematical-format: svg
:mathematical-ppi: 300
endif::[]

ifdef::ebook-format-kf8[]
// Settings for Kindle
endif::[]

////
Do not use ":pygments-css: class" in the block above, as this blocks
the generation and/or display of highlighted code in EPUB output.
Also, the ":pygments-style: xcode" is required, since by default the
EPUB generation uses the "bw" style (i.e., black and white.)
////

= {doctitle}

:sectnums!:

include::chapters/colophon.adoc[]

// Abstract and Dedication MUST have a level-0 heading in EPUB and Kindle
// but level-1 in PDF and HTML
//ifndef::backend-epub3[:leveloffset: +1]
include::chapters/dedication.adoc[]
//ifndef::backend-epub3[:leveloffset: -1]

include::chapters/preface.adoc[]

:sectnums:

ifndef::backend-epub3[]
= Part 1: The Basics

[partintro]
--

This part covers the fundamental concepts of Spark and PySpark.

The following chapters are included:

* Chapter 1: Introduction to PySpark
* Chapter 2: Hello World in PySpark
* Chapter 3: Data Abstractions in PySpark

--
endif::[]

ifndef::backend-epub3[:leveloffset: +1]
include::chapters/chap01.adoc[]

include::chapters/chap02.adoc[]

include::chapters/chap03.adoc[]

ifndef::backend-epub3[:leveloffset: -1]

ifndef::backend-epub3[]
= Part 2: Meet The PySpark: Transformations and Reductions

[partintro]
--

This part covers the fundamental transformations and reductions in Spark.

The following chapters are included:

* Chapter 4: Getting Started with PySpark
* Chapter 5: Spark Transformations with PySpark
* Chapter 6: Reductions in Spark
* Chapter 7: Spark DataFrames

--
endif::[]

ifndef::backend-epub3[:leveloffset: +1]

include::chapters/chap04.adoc[]

include::chapters/chap05.adoc[]

include::chapters/chap06.adoc[]

include::chapters/chap07.adoc[]

ifndef::backend-epub3[:leveloffset: -1]

ifndef::backend-epub3[]
= Part 3: PySpark in High Gear

[partintro]
--
This is PySpark in High Gear.

This part covers some machine learning algorithms,  and basics of data design patterns.

The following chapters are included:

* Chapter 8: Spark Data Sources
* Chapter 9: Logistic Regression
* Chapter 10: Movie Recommendations
* Chapter 11: Graph Algorithms
* Chapter 12: Design Patterns

--
endif::[]

ifndef::backend-epub3[:leveloffset: +1]
include::chapters/chap08.adoc[]

include::chapters/chap09.adoc[]

include::chapters/chap10.adoc[]

include::chapters/chap11.adoc[]

include::chapters/chap12.adoc[]
ifndef::backend-epub3[:leveloffset: -1]

include::chapters/epigraph.adoc[]

include::chapters/appendix_A.adoc[]

include::chapters/appendix_B.adoc[]

include::chapters/appendix_QA.adoc[]

include::chapters/bibliography.adoc[]

ifdef::backend-pdf[]
include::chapters/index.adoc[]
endif::[]

**Comment by mojavelinux** [comment]
This is an EPUB3 converter issue. I'm moving it to that project.
