### ISSUE TITLE
Fails with an exception if a syntax highlighter is used

### ISSUE THREAD

**Issue by rassie** [asciidoctor/asciidoctor-pdf#1231]
In commit https://github.com/asciidoctor/asciidoctor-pdf/commit/4d60ae41cfaa212e3040d1a567afce19b2d68f92 on line 1413: `node.document.syntax_highlighter` is [seemingly not defined for a PDF backend](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/document.rb#L1229). Therefore asciidoctor-pdf throws this exception (I'm using asciidoctor's Docker image):

```
Traceback (most recent call last):
	27: from /usr/bin/asciidoctor-pdf:23:in `<main>'
	26: from /usr/bin/asciidoctor-pdf:23:in `load'
	25: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/bin/asciidoctor-pdf:31:in `<top (required)>'
	24: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	23: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
	22: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	21: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
	20: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
	19: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
	18: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'
	17: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
	16: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/lib/asciidoctor-pdf/converter.rb:127:in `convert'
	15: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/lib/asciidoctor-pdf/converter.rb:268:in `convert_document'
	14: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/lib/asciidoctor-pdf/converter.rb:143:in `convert_content_for_block'
	13: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020:in `content'
	12: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	11: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	10: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	 9: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	 8: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/lib/asciidoctor-pdf/converter.rb:127:in `convert'
	 7: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/lib/asciidoctor-pdf/converter.rb:498:in `convert_section'
	 6: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/lib/asciidoctor-pdf/converter.rb:143:in `convert_content_for_block'
	 5: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	 4: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	 3: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	 2: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	 1: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/lib/asciidoctor-pdf/converter.rb:127:in `convert'
/usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.18/lib/asciidoctor-pdf/converter.rb:1441:in `convert_listing_or_literal': undefined method `highlight?' for nil:NilClass (NoMethodError)
```

**Comment by jstrickler** [comment]
I was just ready to post a message about this. I've been tearing my hair
out. Thanks.

**Comment by mojavelinux** [comment]
Save your hair. I'll have a look tonight.

**Comment by jstrickler** [comment]
Thanks. I know you're a busy guy. And since I have your attention, may I
say thanks so much for this amazing product.

-- John

**Comment by rassie** [comment]
For the sake of completeness: In my case, I haven't had a document title at all, i.e.
```
=== Heading
:source-highlighter: pygments
:pygments-style: manni
:pygments-linenums-mode: inline

dasdajfklöjas djflasd fö *fsajdfkljsad* _fafadsfasdf_ sfasdfa
fasdfdaf
```
Makes no difference to the HTML backend, but apparently to PDF backend. Changing to document header fixes the problem.

**Comment by mojavelinux** [comment]
@rassie You are saying the same thing as me. That's just another way to define attributes outside of the document header.

> Makes no difference to the HTML backend

The logic is a bit more lenient, that's true, but it's still unspecified behavior. The source-highlighter must be defined in the document header.

**Comment by rassie** [comment]
`@rassie You are saying the same thing as me.`

Yeah, I've just added my example for future reference, might help someone one day. Thanks for the help!
