### ISSUE TITLE
Converter aborts when highlighting source using Pygments that contains a quotation mark

### ISSUE THREAD

**Issue by lwolter** [asciidoctor/asciidoctor-pdf#1246]
Sample:
```
= Test yml PDF

[source, yaml]
----
srv123:
  tagabc:
    - value="wert"
----
```

Errormessage:
```
/var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.3/lib/asciidoctor-pdf/converter.rb:3580:in `gsub!': can't modify frozen String (RuntimeError)
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.3/lib/asciidoctor-pdf/converter.rb:3580:in `block in guard_indentation_in_fragments'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.3/lib/asciidoctor-pdf/converter.rb:3577:in `each'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.3/lib/asciidoctor-pdf/converter.rb:3577:in `guard_indentation_in_fragments'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.3/lib/asciidoctor-pdf/converter.rb:1666:in `convert_listing_or_literal'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.3/lib/asciidoctor-pdf/converter.rb:134:in `convert'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/block.rb:111:in `content'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.3/lib/asciidoctor-pdf/converter.rb:150:in `convert_content_for_block'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.3/lib/asciidoctor-pdf/converter.rb:627:in `convert_preamble'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.3/lib/asciidoctor-pdf/converter.rb:134:in `convert'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020:in `content'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.3/lib/asciidoctor-pdf/converter.rb:150:in `convert_content_for_block'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.3/lib/asciidoctor-pdf/converter.rb:258:in `convert_document'
        from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.3/lib/asciidoctor-pdf/converter.rb:134:in `convert'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
        from /var/lib/gems/2.3.0/gems/asciidoctor-2.0.10/bin/asciidoctor:15:in `<top (required)>'
        from /usr/local/bin/asciidoctor:23:in `load'
        from /usr/local/bin/asciidoctor:23:in `<main>'
```

1.5.0.beta.1 does not have this problem.

**Comment by mojavelinux** [comment]
This looks like a follow-up to #1233. Basically, the same issue under a different circumstance.

**Comment by mojavelinux** [comment]
I'll put in a better fix.
