### ISSUE TITLE
Support (or ignore) cellbgcolor using CSS color name

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-pdf#1396]
Now that `cellbgcolor` attribute is used, the following document throws an exception:

```adoc
= Table with cellbgcolor

[%autowidth,cols=3*]
|===
| default background color
| {set:cellbgcolor:red}red background color
| {set:cellbgcolor:white}white background color
|===
```

```console
$ asciidoctor-pdf test.adoc --trace
/home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.2.2/lib/prawn/graphics/color.rb:100:in `color_type': Unknown type of color: "ed" (ArgumentError)
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.2.2/lib/prawn/graphics/color.rb:130:in `color_space'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.2.2/lib/prawn/graphics/color.rb:178:in `set_color'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.2.2/lib/prawn/graphics/color.rb:185:in `set_fill_color'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.2.2/lib/prawn/graphics/color.rb:29:in `fill_color'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:716:in `block in draw_background'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.2.2/lib/prawn/document.rb:650:in `mask'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:715:in `draw_background'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:414:in `block in draw_cells'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:412:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:412:in `draw_cells'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:425:in `ink_and_draw_cells'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:312:in `block in draw'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:680:in `with_position'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:260:in `draw'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:112:in `table'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.beta.7/lib/asciidoctor/pdf/converter.rb:2182:in `convert_table'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.beta.7/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020:in `content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.beta.7/lib/asciidoctor/pdf/converter.rb:154:in `convert_content_for_block'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.beta.7/lib/asciidoctor/pdf/converter.rb:255:in `block in convert_document'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.beta.7/lib/asciidoctor/pdf/converter.rb:563:in `indent_section'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.beta.7/lib/asciidoctor/pdf/converter.rb:212:in `convert_document'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.beta.7/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.beta.7/bin/asciidoctor-pdf:32:in `<top (required)>'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/bin/asciidoctor-pdf:23:in `load'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/bin/asciidoctor-pdf:23:in `<main>'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

As you can see the error message is misleading because the first letter is removed. So at first I thought I made a typo but now I think that CSS color names are not supported right?

```console
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.beta.7 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by mojavelinux** [comment]
Color names are not supported. That is correct. It must be a hex code.

**Comment by Mogztter** [comment]
Maybe we can issue a warning if the color is "unknown" or "invalid"?
And if you want to fail, you can always use `--failure-level` right?

**Comment by mojavelinux** [comment]
Yes, we could throw away an invalid value instead of failing. If you'd like to submit a PR for that, that would be most welcome.
