### ISSUE TITLE
option "-o -" results in encoding error 

### ISSUE THREAD

**Issue by kyochujoho** [asciidoctor/asciidoctor-pdf#1411]
Using the following environment:
```
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.beta.8 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:US-ASCII fs:US-ASCII in:US-ASCII ex:US-ASCII)
```
I have observed this behavior:
```
$ touch foo.adoc
$ asciidoctor-pdf -o - foo.adoc --trace

Traceback (most recent call last):
	22: from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
	21: from /usr/local/bin/asciidoctor-pdf:23:in `load'
	20: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.beta.8/bin/asciidoctor-pdf:27:in `<top (required)>'
	19: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	18: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
	17: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	16: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
	15: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
	14: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
	13: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:124:in `convert'
	12: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:978:in `write'
	11: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf/converter.rb:3556:in `write'
	10: from /var/lib/gems/2.5.0/gems/prawn-2.2.2/lib/prawn/document.rb:378:in `render'
	 9: from /var/lib/gems/2.5.0/gems/pdf-core-0.7.0/lib/pdf/core/renderer.rb:165:in `render'
	 8: from /var/lib/gems/2.5.0/gems/pdf-core-0.7.0/lib/pdf/core/renderer.rb:200:in `render_body'
	 7: from /var/lib/gems/2.5.0/gems/pdf-core-0.7.0/lib/pdf/core/document_state.rb:70:in `render_body'
	 6: from /var/lib/gems/2.5.0/gems/pdf-core-0.7.0/lib/pdf/core/object_store.rb:70:in `each'
	 5: from /var/lib/gems/2.5.0/gems/pdf-core-0.7.0/lib/pdf/core/object_store.rb:70:in `each'
	 4: from /var/lib/gems/2.5.0/gems/pdf-core-0.7.0/lib/pdf/core/object_store.rb:71:in `block in each'
	 3: from /var/lib/gems/2.5.0/gems/pdf-core-0.7.0/lib/pdf/core/document_state.rb:72:in `block in render_body'
	 2: from /usr/lib/ruby/2.5.0/delegate.rb:83:in `method_missing'
	 1: from /usr/lib/ruby/2.5.0/delegate.rb:83:in `<<'
/usr/lib/ruby/2.5.0/delegate.rb:83:in `write': "\x9C" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```
However
```
$ asciidoctor-pdf -o /dev/stdout foo.adoc --trace

<finishes with no error>
```
I suspected this was because my system encoding was not UTF-8, but switching to UTF-8 did not solve it. I've also tried different versions of asciidoctor-pdf, and it does not solve the issue.

It's easy enough to just use /dev/stdout, but I thought it might be good to raise awareness of the issue.

**Comment by mojavelinux** [comment]
You cannot pipe the terminal. A PDF document has binary streams (always the fonts), so that's not going to work, and it's going to look horrible. You need to pipe to a file or another process.

**Comment by kyochujoho** [comment]
Our goal is not to observe the output with terminal. We capture the output and write the data independently, which allows us to write to AWS S3 without saving to the local filesystem of a Docker container.

**Comment by mojavelinux** [comment]
I think I see the problem. The following does not work:

```
asciidoctor-pdf -o - foo.adoc > to-file.pdf
```

In the interim, you can have the converter write to the output file:

```
asciidoctor-pdf -o to-file.pdf foo.adoc
```

**Comment by mojavelinux** [comment]
Turns out this is a regression due to a change in Prawn. I've added a test to the PR to make sure it stays working.
