### ISSUE TITLE
undefined method `checksum' for class `TTFunk::Subset::Base' (NameError)

### ISSUE THREAD

**Issue by andrebauer** [asciidoctor/asciidoctor-pdf#1461]
asciidoctor-pdf fails on my system with the following traceback:

```
$ bundle exec asciidoctor-pdf -v
Traceback (most recent call last):
	11: from /home/andre/repos/github/asciidoctor/asciidoctor-pdf/.bundle/gems/ruby/2.5.0/bin/ruby_executable_hooks:24:in `<main>'
	10: from /home/andre/repos/github/asciidoctor/asciidoctor-pdf/.bundle/gems/ruby/2.5.0/bin/ruby_executable_hooks:24:in `eval'
	 9: from /home/andre/repos/github/asciidoctor/asciidoctor-pdf/.bundle/gems/ruby/2.5.0/bin/asciidoctor-pdf:23:in `<main>'
	 8: from /home/andre/repos/github/asciidoctor/asciidoctor-pdf/.bundle/gems/ruby/2.5.0/bin/asciidoctor-pdf:23:in `load'
	 7: from /home/andre/repos/github/asciidoctor/asciidoctor-pdf/bin/asciidoctor-pdf:5:in `<top (required)>'
	 6: from /home/andre/repos/github/asciidoctor/asciidoctor-pdf/bin/asciidoctor-pdf:5:in `require'
	 5: from /home/andre/repos/github/asciidoctor/asciidoctor-pdf/lib/asciidoctor/pdf.rb:6:in `<top (required)>'
	 4: from /home/andre/repos/github/asciidoctor/asciidoctor-pdf/lib/asciidoctor/pdf.rb:6:in `require_relative'
	 3: from /home/andre/repos/github/asciidoctor/asciidoctor-pdf/lib/asciidoctor/pdf/converter.rb:5:in `<top (required)>'
	 2: from /home/andre/repos/github/asciidoctor/asciidoctor-pdf/lib/asciidoctor/pdf/converter.rb:5:in `require_relative'
	 1: from /home/andre/repos/github/asciidoctor/asciidoctor-pdf/lib/asciidoctor/pdf/ext/ttfunk.rb:4:in `<top (required)>'
/home/andre/repos/github/asciidoctor/asciidoctor-pdf/lib/asciidoctor/pdf/ext/ttfunk.rb:5:in `<class:Base>': undefined method `checksum' for class `TTFunk::Subset::Base' (NameError)
```

```
$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
```

This happens also with other ruby versions, e.g. 2.7.0, and released versions of asciidoctor-pdf, e.g. asciidoctor-pdf-1.5.0.beta.8.

```
$ ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
```

How can i fix this?

**Comment by leonidlezner** [comment]
Having the same issue here. Trying to run asciidoctor-pdf on Github Actions.

```
/opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf/ext/ttfunk.rb:4:in `<class:Base>': undefined method `checksum' for class `TTFunk::Subset::Base' (NameError)
	from /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf/ext/ttfunk.rb:3:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf/converter.rb:4:in `require_relative'
	from /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf/converter.rb:4:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf.rb:5:in `require_relative'
	from /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf.rb:5:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.0.beta.8/bin/asciidoctor-pdf:5:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.6.3/x64/bin/asciidoctor-pdf:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.6.3/x64/bin/asciidoctor-pdf:23:in `<main>'
##[error]Process completed with exit code 1.
```

**Comment by mojavelinux** [comment]
A new version of ttfunk was released today and it broke the API that Asciidoctor PDF uses. While we work out a solution, you can downgrade the version of ttfunk to 1.5.1.

**Comment by mojavelinux** [comment]
This affects the patch for https://github.com/prawnpdf/ttfunk/issues/39, which we may no longer need.

**Comment by andrebauer** [comment]
Thank you, downgrade the version of ttfunk to 1.5.1 helped.
