### ISSUE TITLE
Prawn::Errors::CannotFit introduced in 1.5.0.rc3

### ISSUE THREAD

**Issue by daradermody** [asciidoctor/asciidoctor-pdf#1555]
Though it worked fine in `1.5.0.rc2`, when I upgrade to `1.5.0.rc3` or `1.5.0`, I see this error:
<details>
  <summary>Prawn::Errors::CannotFit</summary>

```
Traceback (most recent call last):
	85: from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
	84: from /usr/local/bin/asciidoctor-pdf:23:in `load'
	83: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/bin/asciidoctor-pdf:27:in `<top (required)>'
	82: from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:111:in `invoke!'
	81: from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:111:in `each'
	80: from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	79: from /usr/lib/ruby/vendor_ruby/asciidoctor/convert.rb:183:in `convert_file'
	78: from /usr/lib/ruby/vendor_ruby/asciidoctor/convert.rb:183:in `open'
	77: from /usr/lib/ruby/vendor_ruby/asciidoctor/convert.rb:183:in `block in convert_file'
	76: from /usr/lib/ruby/vendor_ruby/asciidoctor/convert.rb:118:in `convert'
	75: from /usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:951:in `convert'
	74: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:129:in `convert'
	73: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:205:in `convert_document'
	72: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:587:in `indent_section'
	71: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:258:in `block in convert_document'
	70: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:146:in `traverse'
	69: from /usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:1020:in `content'
	68: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:84:in `content'
	67: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:84:in `map'
	66: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:84:in `block in content'
	65: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:75:in `convert'
	64: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:129:in `convert'
	63: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:577:in `convert_section'
	62: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:146:in `traverse'
	61: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:84:in `content'
	60: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:84:in `map'
	59: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:84:in `block in content'
	58: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:75:in `convert'
	57: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:129:in `convert'
	56: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:577:in `convert_section'
	55: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:146:in `traverse'
	54: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:84:in `content'
	53: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:84:in `map'
	52: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:84:in `block in content'
	51: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:75:in `convert'
	50: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:129:in `convert'
	49: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:577:in `convert_section'
	48: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:146:in `traverse'
	47: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:84:in `content'
	46: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:84:in `map'
	45: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:84:in `block in content'
	44: from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:75:in `convert'
	43: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:129:in `convert'
	42: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/converter.rb:2137:in `convert_table'
	41: from /usr/lib/ruby/vendor_ruby/prawn/table.rb:111:in `table'
	40: from /usr/lib/ruby/vendor_ruby/prawn/table.rb:111:in `new'
	39: from /usr/lib/ruby/vendor_ruby/prawn/table.rb:148:in `initialize'
	38: from /usr/lib/ruby/vendor_ruby/prawn/table.rb:656:in `set_row_heights'
	37: from /usr/lib/ruby/vendor_ruby/prawn/table.rb:369:in `row_heights'
	36: from /usr/lib/ruby/vendor_ruby/prawn/table.rb:369:in `each'
	35: from /usr/lib/ruby/vendor_ruby/prawn/table.rb:373:in `block in row_heights'
	34: from /usr/lib/ruby/vendor_ruby/prawn/table/cell.rb:317:in `height'
	33: from /usr/lib/ruby/vendor_ruby/prawn/table/cell.rb:309:in `height_ignoring_span'
	32: from /usr/lib/ruby/vendor_ruby/prawn/table/cell.rb:336:in `content_height'
	31: from /usr/lib/ruby/vendor_ruby/prawn/table/cell/text.rb:58:in `natural_content_height'
	30: from /usr/lib/ruby/vendor_ruby/prawn/table/cell/text.rb:92:in `with_font'
	29: from /usr/lib/ruby/vendor_ruby/prawn/font.rb:215:in `save_font'
	28: from /usr/lib/ruby/vendor_ruby/prawn/table/cell/text.rb:99:in `block in with_font'
	27: from /usr/lib/ruby/vendor_ruby/prawn/table/cell/text.rb:60:in `block in natural_content_height'
	26: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/box.rb:212:in `render'
	25: from /usr/lib/ruby/vendor_ruby/prawn/font.rb:215:in `save_font'
	24: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/box.rb:213:in `block in render'
	23: from /usr/lib/ruby/vendor_ruby/pdf/core/text.rb:216:in `character_spacing'
	22: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/box.rb:214:in `block (2 levels) in render'
	21: from /var/lib/gems/2.5.0/gems/prawn-templates-0.1.2/lib/prawn/text.rb:19:in `text_rendering_mode'
	20: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/box.rb:219:in `block (3 levels) in render'
	19: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:265:in `font_size'
	18: from /usr/lib/ruby/vendor_ruby/prawn/font.rb:101:in `font_size'
	17: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/box.rb:226:in `block (4 levels) in render'
	16: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/formatted_text/inline_image_arranger.rb:12:in `wrap'
	15: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/wrap.rb:53:in `wrap'
	14: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/line_wrap.rb:47:in `wrap_line'
	13: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/line_wrap.rb:77:in `apply_font_settings_and_add_fragment_to_line'
	12: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/arranger.rb:166:in `apply_font_settings'
	11: from /usr/lib/ruby/vendor_ruby/pdf/core/text.rb:220:in `character_spacing'
	10: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/arranger.rb:175:in `block in apply_font_settings'
	 9: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/arranger.rb:255:in `apply_font_size'
	 8: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.rc.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:265:in `font_size'
	 7: from /usr/lib/ruby/vendor_ruby/prawn/font.rb:101:in `font_size'
	 6: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/arranger.rb:255:in `block in apply_font_size'
	 5: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/line_wrap.rb:78:in `block in apply_font_settings_and_add_fragment_to_line'
	 4: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/line_wrap.rb:93:in `add_fragment_to_line'
	 3: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/line_wrap.rb:93:in `each'
	 2: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/line_wrap.rb:113:in `block in add_fragment_to_line'
	 1: from /usr/lib/ruby/vendor_ruby/prawn/text/formatted/line_wrap.rb:226:in `fragment_finished'
/usr/lib/ruby/vendor_ruby/prawn/text/formatted/line_wrap.rb:243:in `update_output_based_on_last_fragment': Prawn::Errors::CannotFit (Prawn::Errors::CannotFit)
```
</details>

At the moment, I'm trying to zone in on the exact Asciidoc syntax that is resulting in this error (and will update this ticket accordingly), but I was wondering if this might be a known issue considering it was introduced in a specific version.

**Comment by mojavelinux** [comment]
Tables are always going to be tricky since prawn-table has so many problems. Of course, I'll need the precise syntax to be able to tell you more.

Generally, specially, you'll need to be very careful using autowidth tables because it's just not something prawn-table supports well. It's better to specify an explicit width and specific ratios for each column. Then you can steer clear of this type of problem.

**Comment by mojavelinux** [comment]
Chances are it's an image in a table cell somewhere that doesn't fit.

**Comment by daradermody** [comment]
Thanks for the quick support. The syntax is exactly that: images in table cells:
```asciidoc
[cols=", ,",]
|===
|image:image1.png[image] |image:image2.png[image] |image:image3.png[image]
|===
```
I'm not sure what variant of `cols` will work. I've tried specifying the proportions and a width, but I still get the same error:
```asciidoc
[cols="1,1,1"]
[width=100%]
```

**Comment by mojavelinux** [comment]
The problem is the image itself. It's natural size is trying to take up to much space. You need to give each one a width.

Prior to rc3, the width of inline images was computed incorrectly, which is why it was working there.

**Comment by daradermody** [comment]
Great, thanks. It works now that I specify a small enough width for each image:
```
[cols="3*^",frame=none,grid=none]
|===
|image:15d8b8ddb542ae.png[image,pdfwidth=150vw] |image:15d8b8ddb5874a.png[image,pdfwidth=150vw] |image:15d8b8ddb5d491.png[image,pdfwidth=150vw]
|===
```

**Comment by mojavelinux** [comment]
Excellent!

I'll make a note of this in the README.
