### ISSUE TITLE
text_transform doesn't work in table headings

### ISSUE THREAD

**Issue by jduncan-rva** [asciidoctor/asciidoctor-pdf#1575]
```
asciidoctor-pdf --version
Asciidoctor PDF 1.5.2 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
theme has the following content:

```
...
table:
  head:
    text_transform: uppercase
...
```

The following traceback is generated:

```
asciidoctor-pdf -a pdf-themesdir=resources/themes -a pdf-theme=close-report close-report.adoc --trace
Traceback (most recent call last):
	34: from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
	33: from /usr/local/bin/asciidoctor-pdf:23:in `load'
	32: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/bin/asciidoctor-pdf:27:in `<top (required)>'
	31: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	30: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
	29: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	28: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
	27: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
	26: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
	25: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'
	24: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
	23: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	22: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:214:in `convert_document'
	21: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:596:in `indent_section'
	20: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:267:in `block in convert_document'
	19: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:155:in `traverse'
	18: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020:in `content'
	17: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	16: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	15: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	14: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	13: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	12: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:1910:in `convert_table'
	11: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:3790:in `theme_font'
	10: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/ext/prawn/extensions.rb:208:in `font'
	 9: from /Library/Ruby/Gems/2.6.0/gems/prawn-2.2.2/lib/prawn/font.rb:60:in `font'
	 8: from /Library/Ruby/Gems/2.6.0/gems/prawn-2.2.2/lib/prawn/font.rb:215:in `save_font'
	 7: from /Library/Ruby/Gems/2.6.0/gems/prawn-2.2.2/lib/prawn/font.rb:62:in `block in font'
	 6: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:3791:in `block in theme_font'
	 5: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:1962:in `block in convert_table'
	 4: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:1962:in `each'
	 3: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:1963:in `block (2 levels) in convert_table'
	 2: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:1963:in `map'
	 1: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/converter.rb:2043:in `block (3 levels) in convert_table'
/Library/Ruby/Gems/2.6.0/gems/asciidoctor-pdf-1.5.2/lib/asciidoctor/pdf/ext/prawn/extensions.rb:445:in `transform_text': wrong number of arguments (given 1, expected 2) (ArgumentError)
```

The same parameter is used in other places in the theme without known issues.

**Comment by mojavelinux** [comment]
Yep, looks like a typo in the handling of the header cell.

**Comment by mojavelinux** [comment]
Backport to 1.5.x.
