### ISSUE TITLE
asciidoctor-pdf could not embed PNG image under Cygwin

### ISSUE THREAD

**Issue by ljuaneda** [asciidoctor/asciidoctor-pdf#1578]
Hi,

I'm not able to process PNG files :
```
$ asciidoctor-pdf -d book -a pdf-theme=./paas-cap-docs/pdf-themes/bred-default-theme.yml paas-cap-docs/docs/technical_architecture_guide/index.adoc -o technical_architecture_guide.pdf
asciidoctor: WARNING: could not embed image: /cygdrive/e/GDRIVE/BRED/paas-cap-docs/docs/technical_architecture_guide/images/reference_architecture.png; PNG uses unsupported interlace method; install prawn-gmagick gem to add support
```

Here is the Gemfile I've used to install asciidoctor-pdf under cygwin :
```
$ cat Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "asciidoctor"
gem "asciidoctor-pdf"
gem "rouge"
gem "coderay"
gem "pygments.rb"
gem 'prawn', github: 'prawnpdf/prawn'
gem 'prawn-table', github: 'prawnpdf/prawn-table'
gem "prawn-gmagick"
```
Using Bundler :
```
$ bundle
Fetching https://github.com/prawnpdf/prawn
Fetching https://github.com/prawnpdf/prawn-table
Fetching gem metadata from https://rubygems.org/..............
Resolving dependencies...
Using Ascii85 1.0.3
Using public_suffix 4.0.3
Using addressable 2.7.0
Using afm 0.2.2
Using asciidoctor 2.0.10
Using concurrent-ruby 1.1.6
Using pdf-core 0.8.1
Using ttfunk 1.5.1
Using prawn 2.2.2 from https://github.com/prawnpdf/prawn (at master@d980247)
Using prawn-icon 2.5.0
Using css_parser 1.7.1
Using prawn-svg 0.30.0
Using prawn-table 0.2.3 from https://github.com/prawnpdf/prawn-table (at master@515f2db)
Using hashery 2.1.2
Using ruby-rc4 0.1.5
Using pdf-reader 2.4.0
Using prawn-templates 0.1.2
Using safe_yaml 1.0.5
Using thread_safe 0.3.6
Using polyglot 0.3.5
Using treetop 1.6.10
Using asciidoctor-pdf 1.5.2
Using bundler 1.17.2
Using coderay 1.1.2
Using multi_json 1.14.1
Using prawn-gmagick 0.0.9
Using pygments.rb 1.2.1
Using rouge 3.16.0
Bundle complete! 8 Gemfile dependencies, 28 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```
Is there anything am I missing ?

Regards,

Ludovic

**Comment by mojavelinux** [comment]
Can you please provide the image that is causing the problem?

**Comment by mojavelinux** [comment]
When an image cannot be embedded, the message always suggests installing prawn-gmagick, even if it's already loaded. I'll update the code so it only suggests it if it's not in use.

**Comment by mojavelinux** [comment]
When using Bundler, I strongly recommend using the `bundle exec` prefix:

```
bundle exec asciidoctor-pdf -v
```

**Comment by mojavelinux** [comment]
I'm going to turn this into an issue to fix the log message. That way you can know for sure whether or not prawn-gmagick has been loaded.

**Comment by ljuaneda** [comment]
```
$ bundle exec asciidoctor-pdf -v
Asciidoctor PDF 1.5.2 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-cygwin]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

```

and here is the png file :
![reference_architecture](https://user-images.githubusercontent.com/10739749/75521973-1f075080-5a09-11ea-9803-a7813ae6db09.png)

fyi, it's working fine if I just convert the png to jpg....

**Comment by mojavelinux** [comment]
Thanks.

> it's working fine if I just convert the png to jpg

That's because the jpg format doesn't require prawn-gmagick

I'm pretty sure the problem is that even though you've installed the prawn-gmagick gem, it's not on the load path. That's what `bundle exec` does. It makes sure the gems in the Gemfile end up on the load path.

**Comment by ljuaneda** [comment]
I've reset my whole cygwin configuration, still I've got the same issue.

```
$ bundle exec asciidoctor-pdf -v
Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-cygwin]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
$ bundle exec asciidoctor-pdf ./docs/technical_architecture_guide/index.adoc -o ~/GDRIVE/BRED/cap_technical_architecture_guide.pdf
asciidoctor: WARNING: could not embed image: /cygdrive/e/GDRIVE/BRED/paas-cap-docs/docs/technical_architecture_guide/images/reference_architecture.png; PNG uses unsupported interlace method; install prawn-gmagick gem to add support
```

**Comment by mojavelinux** [comment]
That must mean prawn-gmagick doesn't load in your environment.

Can you run both these commands:

bundle exec gem list

and

bundle exec ruby -r prawn-gmagick -e 'puts 1'

>

**Comment by ljuaneda** [comment]
```
$ bundle exec gem list

*** LOCAL GEMS ***

addressable (2.7.0)
afm (0.2.2)
Ascii85 (1.0.3)
asciidoctor (2.0.10)
asciidoctor-pdf (1.5.3)
bundler (default: 1.17.2)
coderay (1.1.2)
concurrent-ruby (1.1.6)
css_parser (1.7.1)
hashery (2.1.2)
multi_json (1.14.1)
pdf-core (0.7.0)
pdf-reader (2.4.0)
polyglot (0.3.5)
prawn (2.2.2)
prawn-gmagick (0.0.9)
prawn-icon (2.5.0)
prawn-svg (0.30.0)
prawn-table (0.2.2)
prawn-templates (0.1.2)
public_suffix (4.0.3)
pygments.rb (1.2.1)
rouge (3.16.0)
ruby-rc4 (0.1.5)
safe_yaml (1.0.5)
thread_safe (0.3.6)
treetop (1.6.10)
ttfunk (1.5.1)

$ bundle exec ruby -r prawn-gmagick -e 'puts 1'
Traceback (most recent call last):
        1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- prawn-gmagick (LoadError)
```

**Comment by mojavelinux** [comment]
Oops, I gave you the wrong command to test. Try this:

```
bundle exec ruby -e "require 'prawn/gmagick'; puts GMagick::Image"
```

**Comment by ljuaneda** [comment]
```
ET85331@CB138737 ~/GDRIVE/BRED/paas-cap-docs
$ bundle exec ruby -e "require 'prawn/gmagick'; puts GMagick::Image"
Could not find prawn-gmagick-0.0.9 in any of the sources
```

**Comment by mojavelinux** [comment]
That likely means it did not install cleanly. It's a native gem, so it requires compiling code during installation. You might try uninstalling and installing again to see if you get any errors or warnings about the install failing.

**Comment by mojavelinux** [comment]
Given that the gem won't load, that establishes this is not an issue with asciidoctor-pdf. I can try to help you debug, but if that doesn't work, you may need to report it to https://github.com/packetmonkey/prawn-gmagick.

**Comment by ljuaneda** [comment]
Yes, you're right :
```
Fetching prawn-gmagick 0.0.9
Installing prawn-gmagick 0.0.9 with native extensions
Building native extensions. This could take a while...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/share/gems/gems/prawn-gmagick-0.0.9/ext/image
/usr/bin/ruby.exe -I /usr/share/rubygems -r ./siteconf20200303-3935-1l4linj.rb extconf.rb
creating Makefile

current directory: /usr/share/gems/gems/prawn-gmagick-0.0.9/ext/image
make "DESTDIR=" clean
rm -f
rm -f image.so  *.o  *.bak mkmf.log .*.time

current directory: /usr/share/gems/gems/prawn-gmagick-0.0.9/ext/image
make "DESTDIR="
gcc -I. -I/usr/include/ruby-2.6 -I/usr/include/ruby-2.6/ruby/backward -I/usr/include/ruby-2.6 -I. -D_XOPEN_SOURCE -D_GNU_SOURCE    -ggdb
-O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4    -o image.o -c
image.c
image.c:3:10: erreur fatale: wand/magick_wand.h : No such file or directory
    3 | #include <wand/magick_wand.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminée.
make: *** [Makefile:246: image.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/share/gems/gems/prawn-gmagick-0.0.9 for inspection.
Results logged to /usr/lib/gems/ruby/2.6/prawn-gmagick-0.0.9/gem_make.out

  /usr/share/rubygems/rubygems/ext/builder.rb:99:in `run'
  /usr/share/rubygems/rubygems/ext/builder.rb:51:in `block in make'
  /usr/share/rubygems/rubygems/ext/builder.rb:43:in `each'
  /usr/share/rubygems/rubygems/ext/builder.rb:43:in `make'
  /usr/share/rubygems/rubygems/ext/ext_conf_builder.rb:62:in `block in build'
  /usr/share/ruby/2.6/tempfile.rb:295:in `open'
  /usr/share/rubygems/rubygems/ext/ext_conf_builder.rb:29:in `build'
  /usr/share/rubygems/rubygems/ext/builder.rb:185:in `block in build_extension'
  /usr/share/ruby/2.6/monitor.rb:235:in `mon_synchronize'
  /usr/share/rubygems/rubygems/ext/builder.rb:181:in `build_extension'
  /usr/share/rubygems/rubygems/ext/builder.rb:229:in `block in build_extensions'
  /usr/share/rubygems/rubygems/ext/builder.rb:226:in `each'
  /usr/share/rubygems/rubygems/ext/builder.rb:226:in `build_extensions'
  /usr/share/rubygems/rubygems/installer.rb:830:in `build_extensions'
  /usr/share/ruby/2.6/bundler/rubygems_gem_installer.rb:23:in `build_extensions'
  /usr/share/rubygems/rubygems/installer.rb:320:in `install'
  /usr/share/ruby/2.6/bundler/source/rubygems.rb:155:in `block in install'
  /usr/share/ruby/2.6/bundler/rubygems_integration.rb:221:in `preserve_paths'
  /usr/share/ruby/2.6/bundler/source/rubygems.rb:144:in `install'
  /usr/share/ruby/2.6/bundler/installer/gem_installer.rb:63:in `install'
  /usr/share/ruby/2.6/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/share/ruby/2.6/bundler/installer/parallel_installer.rb:164:in `do_install'
  /usr/share/ruby/2.6/bundler/installer/parallel_installer.rb:148:in `install_serially'
  /usr/share/ruby/2.6/bundler/installer/parallel_installer.rb:103:in `call'
  /usr/share/ruby/2.6/bundler/installer/parallel_installer.rb:78:in `call'
  /usr/share/ruby/2.6/bundler/installer.rb:289:in `install_in_parallel'
  /usr/share/ruby/2.6/bundler/installer.rb:197:in `install'
  /usr/share/ruby/2.6/bundler/installer.rb:92:in `block in run'
  /usr/share/ruby/2.6/bundler/process_lock.rb:12:in `block in lock'
  /usr/share/ruby/2.6/bundler/process_lock.rb:9:in `open'
  /usr/share/ruby/2.6/bundler/process_lock.rb:9:in `lock'
  /usr/share/ruby/2.6/bundler/installer.rb:73:in `run'
  /usr/share/ruby/2.6/bundler/installer.rb:25:in `install'
  /usr/share/ruby/2.6/bundler/cli/install.rb:65:in `run'
  /usr/share/ruby/2.6/bundler/cli.rb:235:in `block in install'
  /usr/share/ruby/2.6/bundler/settings.rb:143:in `temporary'
  /usr/share/ruby/2.6/bundler/cli.rb:234:in `install'
  /usr/share/ruby/2.6/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/share/ruby/2.6/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/share/ruby/2.6/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /usr/share/ruby/2.6/bundler/cli.rb:27:in `dispatch'
  /usr/share/ruby/2.6/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /usr/share/ruby/2.6/bundler/cli.rb:18:in `start'
  /usr/bin/bundle:30:in `block in <main>'
  /usr/share/ruby/2.6/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  /usr/bin/bundle:22:in `<main>'
```

**Comment by mojavelinux** [comment]
Looks like you need the graphicsmagick development headers.
