### ISSUE TITLE
TypeError when generating PDF

### ISSUE THREAD

**Issue by zhaojunmo** [asciidoctor/asciidoctor-pdf#1607]
Hi, I'd like to thank you for your great software.

I found a TypeError when generating PDF from my adoc file.

My document contains Chinese characters, so I installed `asciidoctor-pdf-cjk-kai_gen_gothic`:
```
gem install --no-document asciidoctor-pdf-cjk-kai_gen_gothic
asciidoctor-pdf-cjk-kai_gen_gothic-install
```

The version:
```
asciidoctor-pdf --version
Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

And this is the command I ran exiting with errors:
```
asciidoctor-pdf  --trace \
  -r asciidoctor-pdf-cjk-kai_gen_gothic \
  -a pdf-style=KaiGenGothicCN \
  manual.adoc

Traceback (most recent call last):
	26: from /usr/bin/asciidoctor-pdf:23:in `<main>'
	25: from /usr/bin/asciidoctor-pdf:23:in `load'
	24: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.3/bin/asciidoctor-pdf:27:in `<top (required)>'
	23: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	22: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
	21: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	20: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
	19: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
	18: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
	17: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'
	16: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
	15: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	14: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:214:in `convert_document'
	13: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:596:in `indent_section'
	12: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:218:in `block in convert_document'
	11: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:2976:in `allocate_toc'
	10: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:873:in `dry_run'
	 9: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:208:in `font'
	 8: from /usr/lib/ruby/gems/2.6.0/gems/prawn-2.2.2/lib/prawn/font.rb:60:in `font'
	 7: from /usr/lib/ruby/gems/2.6.0/gems/prawn-2.2.2/lib/prawn/font.rb:215:in `save_font'
	 6: from /usr/lib/ruby/gems/2.6.0/gems/prawn-2.2.2/lib/prawn/font.rb:62:in `block in font'
	 5: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:874:in `block in dry_run'
	 4: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:874:in `instance_exec'
	 3: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:2978:in `block in allocate_toc'
	 2: from /usr/lib/ruby/gems/2.6.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:481:in `move_down'
	 1: from /usr/lib/ruby/gems/2.6.0/gems/prawn-2.2.2/lib/prawn/document.rb:448:in `move_down'
/usr/lib/ruby/gems/2.6.0/gems/prawn-2.2.2/lib/prawn/document.rb:448:in `-': nil can't be coerced into Float (TypeError)
```

The same adco file worked before(a long time ago), when I try to regenerate the PDF recently, I found this error.

More info:
- My document contains no SVG, but PNG images
- My document contains Chinese characters

**Comment by mojavelinux** [comment]
I'm going to need a sample document in order to help you debug.

What I suspect is that the asciidoctor-pdf-cjk-kai_gen_gothic gem has fallen out of compliance with Asciidoctor PDF. Now that it's so easy to add fonts to the default theme, I recommend making your own theme instead of relying on this gem.

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#extends

Also, when converting Chinese, don't forget to set `-a scripts=cjk` to get proper line breaking behavior (without any extra gems).

**Comment by zhaojunmo** [comment]
@mojavelinux Thank you very much. 
You are right, I don't need asciidoctor-pdf-cjk-kai_gen_gothic anymore. 
What I need to do is to extend the default theme and add my own fonts, problem solved!

**Comment by mojavelinux** [comment]
Fantastic!
