### ISSUE TITLE
Lack of robustess with CJK themes

### ISSUE THREAD

**Issue by andypugh** [asciidoctor/asciidoctor-pdf#1765]
Our english-language docs convert fine. 

But trying to convert Chinese docs fails. 

First failure was with converting admonitions when the theme does not declare a variable: 

```
iMac:src andypugh$ asciidoctor-pdf -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-style=KaiGenGothicJP Master_Getting_Started_cn.txt --trace
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /Users/andypugh/git in PATH, mode 040777
/Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:772:in `convert_admonition': undefined method `/' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:155:in `traverse'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:586:in `convert_section'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020:in `content'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:155:in `traverse'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:267:in `block in convert_document'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:596:in `indent_section'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:214:in `convert_document'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/bin/asciidoctor-pdf:27:in `<top (required)>'
	from /usr/local/bin/asciidoctor-pdf:22:in `load'
	from /usr/local/bin/asciidoctor-pdf:22:in `<main>'
```

This was fixed by uncommenting some variable in the YML. The problem was a commented-out prose:margin. 
Not asciodoctor-pdf's fault, but perhaps there should be a trap? 

Then with that fixed it still errored out with:

```
iMac:src andypugh$ asciidoctor-pdf -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-style=KaiGenGothicCN Master_Getting_Started_cn.txt --trace
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /Users/andypugh/git in PATH, mode 040777
asciidoctor: WARNING: unknown variable reference in PDF theme: $vertical_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $vertical_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $vertical_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $vertical_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $vertical_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $vertical_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $vertical_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $vertical_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $vertical_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $vertical_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $vertical_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $horizontal_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $horizontal_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $vertical_rhythm
asciidoctor: WARNING: unknown variable reference in PDF theme: $horizontal_rhythm
/Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3746:in `>': comparison of Float with String failed (ArgumentError)
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3746:in `margin'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3737:in `margin_bottom'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:2837:in `block in layout_heading'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:604:in `outdent_section'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:2824:in `layout_heading'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:208:in `block in convert_document'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3791:in `block in theme_font'
	from /Library/Ruby/Gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font.rb:62:in `block in font'
	from /Library/Ruby/Gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font.rb:215:in `save_font'
	from /Library/Ruby/Gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font.rb:60:in `font'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:208:in `font'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3790:in `theme_font'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:207:in `convert_document'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.3/bin/asciidoctor-pdf:27:in `<top (required)>'
	from /usr/local/bin/asciidoctor-pdf:22:in `load'
	from /usr/local/bin/asciidoctor-pdf:22:in `<main>'
```

And I gave up.

**Comment by andypugh** [comment]
Source files are here: https://github.com/LinuxCNC/linuxcnc/tree/master/docs/src

And I am aware that the themes and tools used are no longer under active development. I am just suggesting that asciidoctor-pdf could be a little harder to break with changes in these two places.

**Comment by mojavelinux** [comment]
I'm sorry to hear you're having difficulty using Asciidoctor PDF. However, with nearly 1,500 tests and 98% test coverage, I will insist that Asciidoctor PDF is extremely robust. I work very hard to make it that way. Your problem stems from the fact that the CJK theme you're trying to use has not updated to be compatible with the stable release of Asciidoctor PDF (and is thus out of my control).

Fortunately, as the README describes, this theme is no longer necessary. With minimal effort, you can now extend the default theme to register and apply the appropriate CJK fonts. And you can still use the tool provided by the asciidoctor-pdf-cjk-kai_gen_gothic gem to fetch those fonts.

See https://github.com/asciidoctor/asciidoctor-pdf#create-a-custom-cjk-theme for instructions. I just tested it and it converts the document in that repository successfully.

**Comment by mojavelinux** [comment]
Btw, I'm also looking for good sample documents to test CJK support. That repository is going to be very helpful.

**Comment by andypugh** [comment]
It has taken a long time for me to get back to this, but I am preparing an incremental release of our software and I am happy to report that the suggested approach has worked well.

**Comment by mojavelinux** [comment]
I'm happy to hear that!
