### ISSUE TITLE
CannotFit exception when rendering a PDF

### ISSUE THREAD

**Issue by mariuszpala** [asciidoctor/asciidoctor-pdf#1798]
When I try to create a PDF from an .adoc file a get the exception below, generating html works fine. Is there any workaround for it or a way to identify what is wrong?

` asciidoctor-pdf --trace CARA.adoc `

```
Traceback (most recent call last):
	85: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/bin/asciidoctor-pdf:23:in `<main>'
	84: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/bin/asciidoctor-pdf:23:in `load'
	83: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/bin/asciidoctor-pdf:27:in `<top (required)>'
	82: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	81: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
	80: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	79: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
	78: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
	77: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
	76: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'
	75: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
	74: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	73: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:214:in `convert_document'
	72: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:596:in `indent_section'
	71: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:267:in `block in convert_document'
	70: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:155:in `traverse'
	69: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020:in `content'
	68: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	67: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	66: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	65: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	64: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	63: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:586:in `convert_section'
	62: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:155:in `traverse'
	61: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	60: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	59: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	58: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	57: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	56: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:586:in `convert_section'
	55: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:155:in `traverse'
	54: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	53: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	52: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	51: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	50: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	49: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:586:in `convert_section'
	48: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:155:in `traverse'
	47: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	46: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	45: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	44: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	43: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	42: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:2164:in `convert_table'
	41: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table.rb:111:in `table'
	40: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table.rb:111:in `new'
	39: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table.rb:148:in `initialize'
	38: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table.rb:656:in `set_row_heights'
	37: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table.rb:369:in `row_heights'
	36: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table.rb:369:in `each'
	35: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table.rb:373:in `block in row_heights'
	34: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:317:in `height'
	33: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:309:in `height_ignoring_span'
	32: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:336:in `content_height'
	31: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb:58:in `natural_content_height'
	30: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb:92:in `with_font'
	29: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/font.rb:215:in `save_font'
	28: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb:99:in `block in with_font'
	27: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb:60:in `block in natural_content_height'
	26: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:212:in `render'
	25: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/font.rb:215:in `save_font'
	24: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:213:in `block in render'
	23: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/pdf-core-0.7.0/lib/pdf/core/text.rb:214:in `character_spacing'
	22: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:214:in `block (2 levels) in render'
	21: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-templates-0.1.2/lib/prawn/text.rb:19:in `text_rendering_mode'
	20: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:219:in `block (3 levels) in render'
	19: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:265:in `font_size'
	18: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/font.rb:101:in `font_size'
	17: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:226:in `block (4 levels) in render'
	16: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/formatted_text/inline_image_arranger.rb:12:in `wrap'
	15: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/wrap.rb:53:in `wrap'
	14: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:47:in `wrap_line'
	13: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:77:in `apply_font_settings_and_add_fragment_to_line'
	12: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/arranger.rb:166:in `apply_font_settings'
	11: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/pdf-core-0.7.0/lib/pdf/core/text.rb:218:in `character_spacing'
	10: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/arranger.rb:175:in `block in apply_font_settings'
	 9: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/arranger.rb:255:in `apply_font_size'
	 8: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:265:in `font_size'
	 7: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/font.rb:101:in `font_size'
	 6: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/arranger.rb:255:in `block in apply_font_size'
	 5: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:78:in `block in apply_font_settings_and_add_fragment_to_line'
	 4: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:93:in `add_fragment_to_line'
	 3: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:93:in `each'
	 2: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:113:in `block in add_fragment_to_line'
	 1: from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:226:in `fragment_finished'
/usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:243:in `update_output_based_on_last_fragment': Prawn::Errors::CannotFit (Prawn::Errors::CannotFit)
```

**Comment by mojavelinux** [comment]
This is covered in the README. See https://github.com/asciidoctor/asciidoctor-pdf#known-limitations (You would also find an explanation if you searched the issue tracker).

It means an inline image in a table does not specify a width (and thus it tries to take up too much space using the implicit width). Either set the width on the image or switch to an AsciiDoc table cell (and ideally a block image too).

**Comment by mariuszpala** [comment]
Hi @mojavelinux, the problem is that I have no table with images in my doc.

**Comment by mojavelinux** [comment]
I assure you that you do. Otherwise, this line wouldn't appear in the stacktrace.

> from /usr/local/Cellar/asciidoctor/2.0.10_1/libexec/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/formatted_text/inline_image_arranger.rb:12:in `wrap'

So there is an image somewhere.

**Comment by mojavelinux** [comment]
As it turns out, new day, new perspective. I was studying the code again and now I think I can see a way for the size of the image to be forced to fit. I didn't realize that information was available when the image is being arranged. While it may not solve every single case, I think we'll hit most of them.

**Comment by mariuszpala** [comment]
Indeed, I found one cell with an image inside. Thank you

**Comment by mojavelinux** [comment]
:+1: 

I'll continue on with this issue. I think I've found a way to even take into account the width of the image when computing the width of the table cell. The only thing I cannot support properly is a percentage width, since it's a chicken-egg problem. But even that doesn't work well in HTML.

**Comment by mojavelinux** [comment]
I figured it out. It's now possible to support all cases of an inline image that I can think of (with or without an explicit width, in a fixed or autowidth column, and even an image that has a percentage width). PR sent.
