### ISSUE TITLE
 `block in int_to_roman': undefined method `divmod' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by cer** [asciidoctor/asciidoctor-pdf#1839]
This occurs when a document includes a file that has tags without specifying tag filtering `include::foo[]`
Unfortunately, I haven't been able to distill to a simple test case.

```
/Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/helpers.rb:225:in `block in int_to_roman': undefined method `divmod' for nil:NilClass (NoMethodError)
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/helpers.rb:224:in `each'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/helpers.rb:224:in `map'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/helpers.rb:224:in `int_to_roman'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/section.rb:118:in `sectnum'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/section.rb:116:in `sectnum'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/asciidoctor/section.rb:21:in `numbered_title'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3042:in `block (2 levels) in layout_toc_level'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3791:in `block in theme_font'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/prawn-2.2.2/lib/prawn/font.rb:62:in `block in font'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/prawn-2.2.2/lib/prawn/font.rb:215:in `save_font'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/prawn-2.2.2/lib/prawn/font.rb:60:in `font'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:208:in `font'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3790:in `theme_font'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3041:in `block in layout_toc_level'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3039:in `each'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3039:in `layout_toc_level'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3101:in `block (2 levels) in layout_toc_level'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/prawn-2.2.2/lib/prawn/document/bounding_box.rb:286:in `indent'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/prawn-2.2.2/lib/prawn/document.rb:505:in `indent'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3100:in `block in layout_toc_level'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3039:in `each'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3039:in `layout_toc_level'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3025:in `layout_toc'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:2977:in `block in allocate_toc'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:874:in `instance_exec'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:874:in `block in dry_run'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/prawn-2.2.2/lib/prawn/font.rb:62:in `block in font'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/prawn-2.2.2/lib/prawn/font.rb:215:in `save_font'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/prawn-2.2.2/lib/prawn/font.rb:60:in `font'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:208:in `font'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/ext/prawn/extensions.rb:873:in `dry_run'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:2976:in `allocate_toc'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:218:in `block in convert_document'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:596:in `indent_section'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:214:in `convert_document'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:138:in `convert'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/document.rb:1141:in `convert'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1515:in `convert'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `block in convert_file'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `open'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `convert_file'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:129:in `block in invoke!'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:112:in `each'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:112:in `invoke!'
	from /Users/cer/.rvm/gems/ruby-2.4.1/gems/asciidoctor-pdf-1.5.3/bin/asciidoctor-pdf:27:in `<top (required)>'
	from /Users/cer/.rvm/gems/ruby-2.4.1/bin/asciidoctor-pdf:23:in `load'
	from /Users/cer/.rvm/gems/ruby-2.4.1/bin/asciidoctor-pdf:23:in `<main>'
	from /Users/cer/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/cer/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mojavelinux** [comment]
I don't think this has anything to do with includes. It may be something related to what the include is including, but not the include itself. It looks like a problem trying to make the section number, perhaps a part number.

**Comment by mojavelinux** [comment]
The problem is that its trying to make a roman numeral for a part that doesn't have the number property set. The problem is actually coming from Asciidoctor core.

**Comment by mojavelinux** [comment]
Aha. I think I see what the problem is. You seem to have a level-0 section in a document that has sectnums enabled and doctype article. I'm not sure yet why the part doesn't have an internal number.

**Comment by mojavelinux** [comment]
I can't figure out the code path. Do you happen to be using any extensions that might be adding a section to the document programmatically?

**Comment by cer** [comment]
> I can't figure out the code path. Do you happen to be using any extensions that might be adding a section to the document programmatically?

No.

**Comment by mojavelinux** [comment]
Hm. Strange. Let me know when you can reduce this down to an example you can share (or point me to source you're converting).

**Comment by mojavelinux** [comment]
I think this is (or was) a bug in the Asciidoctor core 1.5.x release line. Since Asciidoctor 2, tghe part numeral is no longer generated during the call to Section#sectnum, but rather eagerly when the part is added to the document tree. I think when that change was made, this issue was fixed. Please reopen if you can reproduce using Asciidoctor 2.
