### ISSUE TITLE
getting an install error

### ISSUE THREAD

**Issue by dsisnero** [asciidoctor/asciidoctor-pdf#1847]
gem install asciidoctor-pdf

c:\Users\Dominic E Sisneros\OneDrive - Federal Aviation Administration\Documents\work\projects\nexcom\dominic\BTF_RTR\transmittal>gem install asciidoctor-pdf
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass

**Comment by mojavelinux** [comment]
This is not enough information for me to act on. Can you please specify which Ruby version you are using and show the stacktrace as well.

**Comment by kryops** [comment]
Just got this as well on a fresh installation of Ruby 3.0.0 through RVM, MacOS 11.1.

```
➜  ~ ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
➜  ~ gem -v 
3.2.3
```

```
➜  ~ gem install --backtrace --debug --verbose asciidoctor-pdf               
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `Errno::EISDIR' at /Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/package/file_source.rb:17 - Is a directory @ io_fread - ___.gem
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/asciidoctor-pdf
200 OK
GET https://index.rubygems.org/info/asciidoctor
200 OK
GET https://index.rubygems.org/info/concurrent-ruby
200 OK
GET https://index.rubygems.org/info/prawn
200 OK
GET https://index.rubygems.org/info/prawn-icon
200 OK
GET https://index.rubygems.org/info/prawn-svg
200 OK
GET https://index.rubygems.org/info/prawn-table
200 OK
GET https://index.rubygems.org/info/prawn-templates
200 OK
GET https://index.rubygems.org/info/safe_yaml
200 OK
GET https://index.rubygems.org/info/thread_safe
200 OK
GET https://index.rubygems.org/info/treetop
200 OK
GET https://index.rubygems.org/info/ttfunk
200 OK
GET https://index.rubygems.org/info/css_parser
200 OK
GET https://index.rubygems.org/info/addressable
200 OK
Exception `Gem::Resolver::Molinillo::VersionConflict' at /Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:317 - Unable to satisfy the following requirements:

- `prawn (~> 2.2.0)` required by `asciidoctor-pdf-1.5.3`
- `prawn (< 3, >= 0.11.1)` required by `prawn-svg-0.30.0`
Exception `NoMethodError' at /Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver/conflict.rb:47 - undefined method `request' for nil:NilClass
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver/conflict.rb:47:in `conflicting_dependencies'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/exceptions.rb:32:in `conflicting_dependencies'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/exceptions.rb:26:in `initialize'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `exception'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `raise'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `rescue in resolve'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver.rb:191:in `resolve'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/request_set.rb:411:in `resolve'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/dependency_installer.rb:333:in `resolve_dependencies'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/commands/install_command.rb:198:in `install_gem'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/commands/install_command.rb:223:in `block in install_gems'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/commands/install_command.rb:216:in `each'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/commands/install_command.rb:216:in `install_gems'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/commands/install_command.rb:164:in `execute'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/command.rb:323:in `invoke_with_build_args'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/command_manager.rb:178:in `process_args'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/command_manager.rb:147:in `run'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/gem_runner.rb:53:in `run'
	/Users/strobel/.rvm/rubies/ruby-3.0.0/bin/gem:21:in `<main>'
```

**Comment by mojavelinux** [comment]
Due to limitations in dependencies, you cannot (yet) use this gem with Ruby 3. We're waiting on those dependencies to release new versions. Even then, since we have to upgrade dependencies, it's not likely 1.5.x will support Ruby 3 (it depends, we'll have to see). But you'll definitely be able to use 2.0.x with Ruby 3.

**Comment by mojavelinux** [comment]
For the related issue, see https://github.com/prawnpdf/ttfunk/issues/89

**Comment by dsisnero** [comment]
prawn installs on ruby3 as well as ttfunk

**Comment by mojavelinux** [comment]
Yes, the version just released yesterday. But Asciidoctor PDF depends on specific versions since those programs change a lot between releases. So it will still take time to upgrade and test. And that is likely only going to happen in the master branch (at least, that's where I'll start and we'll see if can backport it to 1.5.x). It's harder than it sounds.

**Comment by mojavelinux** [comment]
I'm closing this issue in favor of #1848 so we have a proper issue for addressing Ruby 3 support.

**Comment by dsisnero** [comment]
Ok- thanks for all the work you do!
