### ISSUE TITLE
Installing Problem

### ISSUE THREAD

**Issue by michaelgrossklos** [asciidoctor/asciidoctor-pdf#1867]
Hi,

when I try to install asciidoctor-pdf, I get this errror:

```
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
```

Google didn't help.

I installed RVM and also used `install bundler` but no difference.

This is what I get when I use the --debug flag:
```
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `Gem::Resolver::Molinillo::VersionConflict' at /Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:317 - Unable to satisfy the following requirements:

- `prawn (~> 2.2.0)` required by `asciidoctor-pdf-1.5.4`
- `prawn (< 3, >= 0.11.1)` required by `prawn-svg-0.31.0`
Exception `NoMethodError' at /Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver/conflict.rb:47 - undefined method `request' for nil:NilClass
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver/conflict.rb:47:in `conflicting_dependencies'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/exceptions.rb:32:in `conflicting_dependencies'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/exceptions.rb:26:in `initialize'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `exception'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `raise'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `rescue in resolve'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/resolver.rb:191:in `resolve'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/request_set.rb:411:in `resolve'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/dependency_installer.rb:333:in `resolve_dependencies'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/commands/install_command.rb:198:in `install_gem'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/commands/install_command.rb:223:in `block in install_gems'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/commands/install_command.rb:216:in `each'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/commands/install_command.rb:216:in `install_gems'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/commands/install_command.rb:164:in `execute'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/command.rb:323:in `invoke_with_build_args'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/command_manager.rb:178:in `process_args'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/command_manager.rb:147:in `run'
	/Users/michael/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/gem_runner.rb:53:in `run'
	/Users/michael/.rvm/rubies/ruby-3.0.0/bin/gem:21:in `<main>'
```

Then I successfully installed prawn manually by using `gem install prawn`. 
The version is 2.4.0. But no difference.

I am on Mac OSX Catalina.

I don't know what else to do.

Thanks for helping!

Michael

**Comment by mojavelinux** [comment]
The 1.5.x release line of Asciidoctor PDF cannot be used with Ruby 3 because the version of Prawn it depends on is not compatible with Ruby 3. Unfortunately, we cannot upgrade Prawn because it prevents the use of older versions of Ruby that this release line still supports. If you need to use Ruby 3, then you'll need to use the code from the master branch of the Asciidoctor PDF repository or wait for a release of Asciidoctor PDF 2. Otherwise, use Ruby 2.7.

**Comment by mojavelinux** [comment]
I will update the README to include this warning.

**Comment by mojavelinux** [comment]
See #1848 for more details.
