### ISSUE TITLE
Override Title page, Font issues

### ISSUE THREAD

**Issue by ModProg** [asciidoctor/asciidoctor-pdf#1921]
Probably due to the font initialization in `layout_title_page`, I get an `not a know font` error, when I try to override it.

(I just copied the implementation for now):

[custom-pdf-converter.rb](https://github.com/asciidoctor/asciidoctor-pdf/files/6409693/custom-pdf-converter.txt)

<details>
  <summary>Stack Trace</summary>

``` stack trace
:!asciidoctor-pdf -r ./custom-pdf-converter.rb expose.adoc --trace

/usr/lib/ruby/gems/3.0.0/gems/prawn-2.4.0/lib/prawn/fonts/afm.rb:57:in `initialize': Noto Serif (normal) is not a known
font. (Prawn::Errors::UnknownFont)
        from /usr/lib/ruby/gems/3.0.0/gems/prawn-2.4.0/lib/prawn/font.rb:313:in `new'
        from /usr/lib/ruby/gems/3.0.0/gems/prawn-2.4.0/lib/prawn/font.rb:313:in `load'
        from /usr/lib/ruby/gems/3.0.0/gems/prawn-2.4.0/lib/prawn/font.rb:252:in `find_font'
        from /usr/lib/ruby/gems/3.0.0/gems/prawn-2.4.0/lib/prawn/font.rb:55:in `font'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/ext/prawn/extensions.rb:208:in `font'
        from /mnt/data/Dokumente/Uni/Bachelor/Arbeit/expose/custom-pdf-converter.rb:28:in `layout_title_page'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:196:in `convert_document'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:139:in `convert'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.15/lib/asciidoctor/document.rb:944:in `convert'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.15/lib/asciidoctor/convert.rb:117:in `convert'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.15/lib/asciidoctor/convert.rb:189:in `block in convert_file'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.15/lib/asciidoctor/convert.rb:189:in `open'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.15/lib/asciidoctor/convert.rb:189:in `convert_file'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.15/lib/asciidoctor/cli/invoker.rb:130:in `block in invoke!'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.15/lib/asciidoctor/cli/invoker.rb:113:in `each'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.15/lib/asciidoctor/cli/invoker.rb:113:in `invoke!'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-1.5.4/bin/asciidoctor-pdf:27:in `<top (required)>'
        from /usr/bin/asciidoctor-pdf:23:in `load'
        from /usr/bin/asciidoctor-pdf:23:in `<main>'
```

</details>

The relevant line is:
```rb
    # NOTE: this is the first page created, so we must set the base font
    font @theme.base_font_family, size: @root_font_size, style: @theme.base_font_style
```

**Comment by mojavelinux** [comment]
I think you may have copied the code from the wrong branch. If you are using 1.5.x, then you need to copy the code from: https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.4/lib/asciidoctor/pdf/converter.rb

**Comment by mojavelinux** [comment]
For help using and extending Asciidoctor PDF, please direct questions to the community chat at https://asciidoctor.zulipchat.com.
