### ISSUE TITLE
pdf creation fails when using a codeblock that ends with '\' but has no following line with content 

### ISSUE THREAD

**Issue by mmattel** [asciidoctor/asciidoctor-pdf#1930]
I ran into a strange issue which drove me nuts to find out the cause.

**Issue:**
Building a pdf always prompted an error, _while building html works flawless_:
```
undefined method `strip' for nil:NilClass
  Use --trace for backtrace
```

It turned out that following codeblock is problematic:
```
[source,console]
----
QT_LOGGING_RULES='gui.socketapi=false;sync.database*=false' \
  /PATH/TO/CLIENT \
----
```
When removing the trailing backslash `\` in the second line, pdf building works as expected. This is how it gets rendered when removing the backslash:
![image](https://user-images.githubusercontent.com/3321281/117944831-f6b5fa00-b30d-11eb-8504-fb9026ea559a.png)

It seems, that when a line code block ends with `\` but has no following line with content, buildig fails. This behaviour may be technically correct when using eg a bash command when you split into multiple lines, but in my understanding, a codeblock should be taken as it is and printed without parsing or syntax highlighting.

**asciidoctor-pdf version:**
```
asciidoctor-pdf --version
Asciidoctor PDF 1.5.4 using Asciidoctor 2.0.12 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
**Trace:**
```
Traceback (most recent call last):
	60: from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
	59: from /usr/local/bin/asciidoctor-pdf:23:in `load'
	58: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/bin/asciidoctor-pdf:27:in `<top (required)>'
	57: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/invoker.rb:110:in `invoke!'
	56: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:117:in `convert'
	55: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
	54: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:139:in `convert'
	53: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:215:in `convert_document'
	52: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:598:in `indent_section'
	51: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:268:in `block in convert_document'
	50: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:156:in `traverse'
	49: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:1005:in `content'
	48: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	47: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	46: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	45: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	44: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:139:in `convert'
	43: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:588:in `convert_section'
	42: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:156:in `traverse'
	41: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	40: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	39: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	38: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	37: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:139:in `convert'
	36: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:588:in `convert_section'
	35: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:156:in `traverse'
	34: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	33: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	32: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	31: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	30: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:139:in `convert'
	29: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:588:in `convert_section'
	28: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:156:in `traverse'
	27: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	26: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	25: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	24: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	23: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:139:in `convert'
	22: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:588:in `convert_section'
	21: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:156:in `traverse'
	20: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	19: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	18: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	17: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	16: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:139:in `convert'
	15: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:588:in `convert_section'
	14: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:156:in `traverse'
	13: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	12: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	11: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	10: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	 9: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:139:in `convert'
	 8: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:1762:in `convert_listing_or_literal'
	 7: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/ext/rouge/formatters/prawn.rb:50:in `format'
	 6: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/ext/rouge/formatters/prawn.rb:103:in `stream'
	 5: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/ext/rouge/formatters/prawn.rb:103:in `map'
	 4: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/ext/rouge/formatters/prawn.rb:103:in `each'
	 3: from /var/lib/gems/2.5.0/gems/rouge-3.26.0/lib/rouge/lexer.rb:470:in `lex'
	 2: from /var/lib/gems/2.5.0/gems/rouge-3.26.0/lib/rouge/lexer.rb:480:in `continue_lex'
	 1: from /var/lib/gems/2.5.0/gems/rouge-3.26.0/lib/rouge/lexers/console.rb:186:in `stream_tokens'
/var/lib/gems/2.5.0/gems/rouge-3.26.0/lib/rouge/lexers/console.rb:147:in `process_line': undefined method `strip' for nil:NilClass (NoMethodError)
```

**Comment by mojavelinux** [comment]
This is a bug in Rouge. In fact, I have already reported it. See https://github.com/rouge-ruby/rouge/issues/1602
