### ISSUE TITLE
Image description issue: nil can't be coerced into Integer (TypeError)

### ISSUE THREAD

**Issue by mmattel** [asciidoctor/asciidoctor-pdf#1970]
I ran into following issue driving me nuts...

When using 
`image:my_image.png[text text, text text]`
you get the error shown below.

Yes, the image description text should not contain commas as post the comma you can add eg sizing directives, but

it would be good to have a better error message than `nil can't be coerced into Integer (TypeError)` pointing to the possible cause. Like: expecting a directive post the comma at "descriptive text" but none found. Maybe you find a way to improve it.

```
Traceback (most recent call last):
	52: from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
	51: from /usr/local/bin/asciidoctor-pdf:23:in `load'
	50: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/bin/asciidoctor-pdf:27:in `<top (required)>'
	49: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/invoker.rb:110:in `invoke!'
	48: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:117:in `convert'
	47: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
	46: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:135:in `convert'
	45: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:208:in `convert_document'
	44: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:594:in `indent_section'
	43: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:261:in `block in convert_document'
	42: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:152:in `traverse'
	41: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:1005:in `content'
	40: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	39: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	38: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	37: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	36: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:135:in `convert'
	35: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:584:in `convert_section'
	34: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:152:in `traverse'
	33: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	32: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	31: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	30: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	29: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:135:in `convert'
	28: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:708:in `convert_paragraph'
	27: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:2858:in `layout_prose'
	26: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:3901:in `typeset_text'
	25: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text.rb:167:in `text'
	24: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text.rb:216:in `formatted_text'
	23: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/ext/prawn/extensions.rb:376:in `fill_formatted_text_box'
	22: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/box.rb:214:in `render'
	21: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/font.rb:214:in `save_font'
	20: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/box.rb:215:in `block in render'
	19: from /var/lib/gems/2.5.0/gems/pdf-core-0.9.0/lib/pdf/core/text.rb:227:in `character_spacing'
	18: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/box.rb:216:in `block (2 levels) in render'
	17: from /var/lib/gems/2.5.0/gems/prawn-templates-0.1.2/lib/prawn/text.rb:19:in `text_rendering_mode'
	16: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/box.rb:221:in `block (3 levels) in render'
	15: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/ext/prawn/extensions.rb:265:in `font_size'
	14: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/font.rb:100:in `font_size'
	13: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/box.rb:229:in `block (4 levels) in render'
	12: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/formatted_text/inline_image_arranger.rb:12:in `wrap'
	11: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/wrap.rb:55:in `wrap'
	10: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:49:in `wrap_line'
	 9: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:79:in `apply_font_settings_and_add_fragment_to_line'
	 8: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/arranger.rb:183:in `apply_font_settings'
	 7: from /var/lib/gems/2.5.0/gems/pdf-core-0.9.0/lib/pdf/core/text.rb:227:in `character_spacing'
	 6: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/arranger.rb:193:in `block in apply_font_settings'
	 5: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/arranger.rb:272:in `apply_font_size'
	 4: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:80:in `block in apply_font_settings_and_add_fragment_to_line'
	 3: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:96:in `add_fragment_to_line'
	 2: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:96:in `each'
	 1: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:104:in `block in add_fragment_to_line'
/var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:104:in `+': nil can't be coerced into Integer (TypeError)
```

**Comment by mojavelinux** [comment]
Thanks for bringing this to my attention. The correct behavior is that the invalid width is simply ignored. Though I will consider the possibility of logging a warning message about it. I'll give it some thought.

**Comment by mmattel** [comment]
When doing your brainstorming, consider that a warning message should contain what image desccription is in doubt and why - else you never will find the erroring text and the ability to correct it.

**Comment by mojavelinux** [comment]
The message would look like any other image warning message...which already includes that information.

**Comment by mojavelinux** [comment]
I've decided to make the converter ignore the value instead of warn. AsciiDoc is a forgiving syntax and the converter is receiving a width value that can't be parsed as a number. It's too late at this point to give location information about the image, and really it's not the converter's responsibility to do so. If you want validation, it should either happen in the core processor or in an external tool. What the converter can do is degrade gracefully by ignoring the invalid value.
