### ISSUE TITLE
A commented line gets checked and errors are thrown

### ISSUE THREAD

**Issue by mmattel** [asciidoctor/asciidoctor-pdf#1971]
I ran into following issue:

Images were not able to be rendered with the width set and an error was thrown: `Prawn::Errors::CannotFit`

After fiddling around I tried to comment **all** lines containing `image:...`, but the error was still thrown - this is strange as comments should not get checked.

I had to go in that document, set all width to a very low value and raised image by image (many) the width value, which ended up that the width of 60% of images in a table with 2 columns caused the error.

```
^| image:my_image1.png[text, width=60%,pdfwidth=60%]
^| image:my_image2.pngtext, width=60%,pdfwidth=60%]
```

There are now two issues:
1. why do lines get processed if they are set to comment with `// image: ....`
Note that running a html build does not render commented lines (checked)
2. why is there no error message where the incident occurs (the image text)

```
Traceback (most recent call last):
	79: from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
	78: from /usr/local/bin/asciidoctor-pdf:23:in `load'
	77: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/bin/asciidoctor-pdf:27:in `<top (required)>'
	76: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/invoker.rb:110:in `invoke!'
	75: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:117:in `convert'
	74: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
	73: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:135:in `convert'
	72: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:208:in `convert_document'
	71: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:594:in `indent_section'
	70: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:261:in `block in convert_document'
	69: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:152:in `traverse'
	68: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:1005:in `content'
	67: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	66: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	65: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	64: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	63: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:135:in `convert'
	62: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:584:in `convert_section'
	61: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:152:in `traverse'
	60: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	59: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	58: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	57: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	56: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:135:in `convert'
	55: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:584:in `convert_section'
	54: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:152:in `traverse'
	53: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	52: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	51: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	50: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	49: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:135:in `convert'
	48: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:584:in `convert_section'
	47: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:152:in `traverse'
	46: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	45: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	44: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	43: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	42: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:135:in `convert'
	41: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:2163:in `convert_table'
	40: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:111:in `table'
	39: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:111:in `new'
	38: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:148:in `initialize'
	37: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:656:in `set_row_heights'
	36: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:369:in `row_heights'
	35: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:369:in `each'
	34: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:373:in `block in row_heights'
	33: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:317:in `height'
	32: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:309:in `height_ignoring_span'
	31: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:336:in `content_height'
	30: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb:58:in `natural_content_height'
	29: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb:92:in `with_font'
	28: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/font.rb:214:in `save_font'
	27: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb:99:in `block in with_font'
	26: from /var/lib/gems/2.5.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb:60:in `block in natural_content_height'
	25: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/box.rb:214:in `render'
	24: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/font.rb:214:in `save_font'
	23: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/box.rb:215:in `block in render'
	22: from /var/lib/gems/2.5.0/gems/pdf-core-0.9.0/lib/pdf/core/text.rb:227:in `character_spacing'
	21: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/box.rb:216:in `block (2 levels) in render'
	20: from /var/lib/gems/2.5.0/gems/prawn-templates-0.1.2/lib/prawn/text.rb:19:in `text_rendering_mode'
	19: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/box.rb:221:in `block (3 levels) in render'
	18: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/ext/prawn/extensions.rb:265:in `font_size'
	17: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/font.rb:100:in `font_size'
	16: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/box.rb:229:in `block (4 levels) in render'
	15: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/formatted_text/inline_image_arranger.rb:12:in `wrap'
	14: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/wrap.rb:55:in `wrap'
	13: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:49:in `wrap_line'
	12: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:79:in `apply_font_settings_and_add_fragment_to_line'
	11: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/arranger.rb:183:in `apply_font_settings'
	10: from /var/lib/gems/2.5.0/gems/pdf-core-0.9.0/lib/pdf/core/text.rb:231:in `character_spacing'
	 9: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/arranger.rb:193:in `block in apply_font_settings'
	 8: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/arranger.rb:274:in `apply_font_size'
	 7: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/ext/prawn/extensions.rb:265:in `font_size'
	 6: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/font.rb:100:in `font_size'
	 5: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:80:in `block in apply_font_settings_and_add_fragment_to_line'
	 4: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:96:in `add_fragment_to_line'
	 3: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:96:in `each'
	 2: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:117:in `block in add_fragment_to_line'
	 1: from /var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:231:in `fragment_finished'
/var/lib/gems/2.5.0/gems/prawn-2.4.0/lib/prawn/text/formatted/line_wrap.rb:248:in `update_output_based_on_last_fragment': Prawn::Errors::CannotFit (Prawn::Errors::CannotFit)
```

**Comment by mojavelinux** [comment]
The problem you are encountering regarding the image not fitting is documented at the top of the README as a limitation of Asciidoctor PDF:

> An inline image in a table cell will not force the column wider if the width of the image exceeds the width of the column; either reduce the image width using pdfwidth, increase the width of the column using cols, or convert the cell to an AsciiDoc table cell (see asciidoctor/asciidoctor-pdf/issues/830).

When putting an image in a table cell, you should almost always use an AsciiDoc table cell and, even better, make it a block image. If you don't use an AsciiDoc table cell, the image has to fit within the width you have allocated for the column. If it doesn't, you get the error you see.

> as comments should not get checked.

I assure you that comments do not get checked. Something must be incorrect about the syntax you are using for your line comment. I can't tell what you are entering based on the example you have provided.

> why is there no error message where the incident occurs (the image text)

When Asciidoctor PDF crashes, this is just how it works. It's too late in a converter to provide line information from the source document. And the "cannot fit" errors happen deep inside of prawn-table where we cannot anticipate and catch them. That's not going to change.

**Comment by mmattel** [comment]
With the help of your comment regarding images in tables and ad-pdf, I fixed them all and the pdf build is working now correctly, images are shown as expected. Even after years of using Antora/ad-pdf I am still learning 😄 

Regarding the comment line issue, I have to recheck

**Comment by mojavelinux** [comment]
> Images were not able to be rendered with the width set and an error was thrown: Prawn::Errors::CannotFit

Asciidoctor PDF 2 will now log this at the error level and, if the sourcemap is enabled, report the file and line number of the table. See #2009.
