### ISSUE TITLE
asciidoctor-pdf installed (?) but won't run

### ISSUE THREAD

**Issue by wolandscat** [asciidoctor/asciidoctor-pdf#208]
Asciidoctor-pdf installation worked fine apparently:
```
$ gem install --pre asciidoctor-pdf
Fetching: polyglot-0.3.5.gem (100%)
Successfully installed polyglot-0.3.5
Fetching: treetop-1.5.3.gem (100%)
Successfully installed treetop-1.5.3
Fetching: thread_safe-0.3.4.gem (100%)
Successfully installed thread_safe-0.3.4
Fetching: safe_yaml-1.0.4.gem (100%)
Successfully installed safe_yaml-1.0.4
Fetching: pdf-core-0.2.5.gem (100%)
Successfully installed pdf-core-0.2.5
Fetching: ttfunk-1.2.2.gem (100%)
Successfully installed ttfunk-1.2.2
Fetching: prawn-1.2.1.gem (100%)

  ********************************************


  A lot has changed recently in Prawn.

  Please read the changelog for details:

  https://github.com/prawnpdf/prawn/wiki/CHANGELOG


  ********************************************

Successfully installed prawn-1.2.1
Fetching: prawn-icon-0.6.4.gem (100%)
Successfully installed prawn-icon-0.6.4
Fetching: addressable-2.3.8.gem (100%)
Successfully installed addressable-2.3.8
Fetching: css_parser-1.3.6.gem (100%)
Successfully installed css_parser-1.3.6
Fetching: prawn-svg-0.18.0.gem (100%)
Successfully installed prawn-svg-0.18.0
Fetching: Ascii85-1.0.2.gem (100%)
Successfully installed Ascii85-1.0.2
Fetching: ruby-rc4-0.1.5.gem (100%)
Successfully installed ruby-rc4-0.1.5
Fetching: hashery-2.1.1.gem (100%)
Successfully installed hashery-2.1.1
Fetching: afm-0.2.2.gem (100%)
Successfully installed afm-0.2.2
Fetching: pdf-reader-1.3.3.gem (100%)

  ********************************************

  v1.0.0 of PDF::Reader introduced a new page-based API. There are extensive
  examples showing how to use it in the README and examples directory.

  For detailed documentation, check the rdocs for the PDF::Reader,
  PDF::Reader::Page and PDF::Reader::ObjectHash classes.

  The old API is marked as deprecated but will continue to work with no
  visible warnings for now.

  ********************************************

Successfully installed pdf-reader-1.3.3
Fetching: prawn-templates-0.0.3.gem (100%)
Successfully installed prawn-templates-0.0.3
Fetching: prawn-table-0.1.1.gem (100%)

  ********************************************


  A lot has changed recently in Prawn.

  Please read the changelog for details:

  https://github.com/prawnpdf/prawn/wiki/CHANGELOG


  ********************************************

Successfully installed prawn-table-0.1.1
Fetching: asciidoctor-pdf-1.5.0.alpha.7.gem (100%)
Successfully installed asciidoctor-pdf-1.5.0.alpha.7
Parsing documentation for polyglot-0.3.5
Installing ri documentation for polyglot-0.3.5
Parsing documentation for treetop-1.5.3
Installing ri documentation for treetop-1.5.3
Parsing documentation for thread_safe-0.3.4
Installing ri documentation for thread_safe-0.3.4
Parsing documentation for safe_yaml-1.0.4
Installing ri documentation for safe_yaml-1.0.4
Parsing documentation for pdf-core-0.2.5
Installing ri documentation for pdf-core-0.2.5
Parsing documentation for ttfunk-1.2.2
Installing ri documentation for ttfunk-1.2.2
Parsing documentation for prawn-1.2.1
Installing ri documentation for prawn-1.2.1
Parsing documentation for prawn-icon-0.6.4
Installing ri documentation for prawn-icon-0.6.4
Parsing documentation for addressable-2.3.8
Installing ri documentation for addressable-2.3.8
Parsing documentation for css_parser-1.3.6
Installing ri documentation for css_parser-1.3.6
Parsing documentation for prawn-svg-0.18.0
Installing ri documentation for prawn-svg-0.18.0
Parsing documentation for Ascii85-1.0.2
Installing ri documentation for Ascii85-1.0.2
Parsing documentation for ruby-rc4-0.1.5
Installing ri documentation for ruby-rc4-0.1.5
Parsing documentation for hashery-2.1.1
Installing ri documentation for hashery-2.1.1
Parsing documentation for afm-0.2.2
Installing ri documentation for afm-0.2.2
Parsing documentation for pdf-reader-1.3.3
Installing ri documentation for pdf-reader-1.3.3
Parsing documentation for prawn-templates-0.0.3
Installing ri documentation for prawn-templates-0.0.3
Parsing documentation for prawn-table-0.1.1
Installing ri documentation for prawn-table-0.1.1
Parsing documentation for asciidoctor-pdf-1.5.0.alpha.7
Installing ri documentation for asciidoctor-pdf-1.5.0.alpha.7
Done installing documentation for polyglot, treetop, thread_safe, safe_yaml, pdf                                                                       -core, ttfunk, prawn, prawn-icon, addressable, css_parser, prawn-svg, Ascii85, r                                                                       uby-rc4, hashery, afm, pdf-reader, prawn-templates, prawn-table, asciidoctor-pdf                                                                        after 21 seconds
19 gems installed
```

Try to run asciidoctor-pdf
```
$ asciidoctor-pdf -v
/usr/share/rubygems/rubygems/dependency.rb:315:in `to_specs': Could not find 'asciidoctor-pdf' (>= 0) among 15 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/Thomas/.gem/ruby:/usr/share/gems:/usr/local/share/gems', execute `gem env` for more information
        from /usr/share/rubygems/rubygems/dependency.rb:324:in `to_spec'
        from /usr/share/rubygems/rubygems/core_ext/kernel_gem.rb:64:in `gem'
        from /usr/local/bin/asciidoctor-pdf:22:in `<main>'
```

For some reason the GEM_PATH above doesn't include /usr/local, which is where the asciidoctor-pdf installed itself (i.e. in /usr/local/gems). But gem env returns this (see GEM PATHs):

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.7
  - RUBY VERSION: 2.2.2 (2015-04-13 patchlevel 95) [x86_64-cygwin]
  - INSTALLATION DIRECTORY: /usr/local
  - RUBY EXECUTABLE: /usr/bin/ruby.exe
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/Thomas/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-cygwin
  - GEM PATHS:
     - /usr/local
     - /home/Thomas/.gem/ruby
     - /usr/share/gems
     - /usr/local/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gemhome" => "/usr/local"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/bin
     - /cygdrive/c/ProgramData/Oracle/Java/javapath
     - /cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common
     - /cygdrive/c/Program Files (x86)/Intel/iCLS Client
     - /cygdrive/c/Program Files/Intel/iCLS Client
     - /cygdrive/c/Windows/system32
     - /cygdrive/c/Windows
     - /cygdrive/c/Windows/System32/Wbem
     - /cygdrive/c/Windows/System32/WindowsPowerShell/v1.0
     - /cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL
     - /cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT
     - /cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL
     - /cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT
     - /cygdrive/c/Program Files/Intel/WiFi/bin
     - /cygdrive/c/Program Files/Common Files/Intel/WirelessCommon
     - /cygdrive/c/Program Files (x86)/GitExtensions
     - /cygdrive/c/Program Files/Eiffel Software/EiffelStudio 14.05 GPL/library/gobo/spec/win64/bin
     - /cygdrive/c/Program Files (x86)/Skype/Phone
     - /cygdrive/c/Program Files/Saxonica/SaxonHE9.4N/bin
     - /usr/lib/lapack
```

Hopefully just a ruby config / install problem, but one I imagine could happen to anyone - my cygwin env is pretty clean and up to date. I also have never had ruby until installing asciidoctor, so all the ruby installation is new as well.

Any thoughts?

**Comment by mojavelinux** [comment]
This seems to be a Cygwin issue. See https://www.cygwin.com/ml/cygwin/2014-11/msg00377.html

My guess is that the base install just doesn't setup environment variables correctly for Ruby, so you hit it the very first time you try to do anything with Ruby. Fedora had this problem once, so it's not uncommon. The solution is to figure out where the cli script ended up (maybe ~/bin) and add that path to your PATH.

**Comment by wolandscat** [comment]
The same problem affects many ruby things under cygwin apparently. Here's the same report and a fix for vagrant - https://github.com/mitchellh/vagrant/issues/1304 . I could possibly make this fix, but I have no idea about anything ruby - can someone provide a hint to where the equivalent asciidoctor-pdf install script (is that what I am looking for?) lives? Also, could an issue be raised to make this same fix permanent for asciidoctor-pdf (assuming it is applicable)?

**Comment by mojavelinux** [comment]
A gem should not modify the environment. This is really an issue with how Cygwin is setup. I'll explain the situation and how I was able to resolve it in a Cygwin.

By default, the `gem install` command as configured on Cygwin will install gem libraries to your home directory under the following directory:

$HOME/.gem/ruby

It will also install launch scripts (called binstubs) in the following directory:

$HOME/bin

(This behavior is pretty typical default behavior on Linux too, though some distributions modify it).

**Solution 1:**

Thus, to get the launch scripts on your path, all you need to do within Cygwin is run:

    $ export PATH="$HOME/bin:$PATH"

You can put this in your bash profile (`$HOME/.profile`) to make it permanent.

**Solution 2:**

If you want the gem to be installed in a different location, you can change it using the `.gemrc` configuration file (as described at https://blogs.oracle.com/mandy/entry/rubygems_etc_gemrc) or, better yet, by setting the `$GEM_HOME` environment variable in your bash profile (as described in http://stackoverflow.com/questions/11277227/whats-the-difference-between-gem-home-and-gem-path)

You can also modify the configuration per invocation of `gem install`. See http://guides.rubygems.org/command-reference/#gem-install.

**Solution 3:**

Another solution is to install the gem as the root user. Then, the gem will be installed into the system (with the launch script put in /usr/bin) and thus immediately available.

**Solution 4 (my preferred solution):**

You can avoid all of this nightmare by using RVM. RVM manages the whole Ruby environment for you in a sane way, including setting the `$GEM_PATH` environment variable. I always use RVM when I use Ruby and I avoid a lot of headaches as a result.

**Comment by mojavelinux** [comment]
I discovered that you can force the gems to install into the system on Cygwin by doing the following.

 $ export GEM_HOME=/usr/share/gems

In this case, the binstubs will end up in /usr/share/gems/bin, which you need to add to your PATH:

 $ export PATH="/usr/share/gems/bin:$PATH"

The advantage of installing your own gems into your home directory, though, is that they are kept separate from the system gems (installed with the package manager). Again, RVM also helps make this distinction.

**Comment by wolandscat** [comment]
I now have the environment working. Recommend some getting-started pages on rub/gem/rvm set up for non ruby people who don't know any better.

**Comment by mojavelinux** [comment]
:+1: I'll file a follow-up issue in the asciidoctor.org repository to cover this.
