### ISSUE TITLE
undefined method intrinsic_image_dimensions when calling convert_inline_image

### ISSUE THREAD

**Issue by softmetz** [asciidoctor/asciidoctor-pdf#2228]
When I run latest Asciidoctor (2.0.17) and Asciidoctor-pdf (2.0.6) on Ruby 3.0.2 (in Almalinux 8, appstream), it fails for files with images with the message in `convert_inline_image': undefined method `intrinsic_image_dimensions'

Trace is 

```
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-pdf-2.0.6/lib/asciidoctor/pdf/converter.rb:147:in `convert'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/inline.rb:32:in `convert'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/substitutors.rb:430:in `block in sub_macros'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/substitutors.rb:414:in `gsub'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/substitutors.rb:414:in `sub_macros'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/substitutors.rb:102:in `block in apply_subs'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/substitutors.rb:91:in `each'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/substitutors.rb:91:in `apply_subs'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/abstract_block.rb:289:in `title'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/document.rb:723:in `doctitle'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-pdf-2.0.6/lib/asciidoctor/pdf/converter.rb:3988:in `resolve_doctitle'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-pdf-2.0.6/lib/asciidoctor/pdf/converter.rb:517:in `build_pdf_info'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-pdf-2.0.6/lib/asciidoctor/pdf/converter.rb:507:in `build_pdf_options'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-pdf-2.0.6/lib/asciidoctor/pdf/converter.rb:334:in `init_pdf'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-pdf-2.0.6/lib/asciidoctor/pdf/converter.rb:158:in `convert_document'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-pdf-2.0.6/lib/asciidoctor/pdf/converter.rb:147:in `convert'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/document.rb:955:in `convert'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:118:in `convert'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:190:in `block in convert_file'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:190:in `open'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:190:in `convert_file'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/cli/invoker.rb:129:in `block in invoke!'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/cli/invoker.rb:112:in `each'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-2.0.17/lib/asciidoctor/cli/invoker.rb:112:in `invoke!'
        from /home/ci/.local/share/gem/ruby/gems/asciidoctor-pdf-2.0.6/bin/asciidoctor-pdf:27:in `<top (required)>'
        from /home/ci/bin/asciidoctor-pdf:23:in `load'
        from /home/ci/bin/asciidoctor-pdf:23:in `<main>'
```

**Comment by mojavelinux** [comment]
Can you please provide the document or image that triggers this error?

**Comment by mojavelinux** [comment]
I think the issue may be when an inline image is used in a title, which gets converted before the converter is initialized.

**Comment by softmetz** [comment]
Seems very likely. Here is a document to reproduce it. Thank you!

[asciidoc-title-image.tar.gz](https://github.com/asciidoctor/asciidoctor-pdf/files/8827135/asciidoc-title-image.tar.gz)

**Comment by mojavelinux** [comment]
Thanks. I see the problem. The convert_inline_image is being called before the intrinsic_image_dimensions method gets defined in the converter. I'll need to shift some things around. Thanks for the report!
