### ISSUE TITLE
Exception while trying to generate PDF using a-m-p 1.5.2.1

### ISSUE THREAD

**Issue by dashorst** [asciidoctor/asciidoctor-pdf#229]
Using latest release of asciidoctor-pdf (1.5.0-alpha7), asciidoctor-maven-plugin and jruby (1.7.20) we get the following error. We use the default theme.

```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:process-asciidoc (generate-pdf-doc) on project asciidoc-to-html-example: Execution generate-pdf-doc of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:process-asciidoc failed: (NoMethodError) undefined method `each' for nil:NilClass -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:process-asciidoc (generate-pdf-doc) on project asciidoc-to-html-example: Execution generate-pdf-doc of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:process-asciidoc failed: (NoMethodError) undefined method `each' for nil:NilClass
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-pdf-doc of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:process-asciidoc failed: (NoMethodError) undefined method `each' for nil:NilClass
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `each' for nil:NilClass
        at RUBY.layout_running_content(/home/beltman/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.7/asciidoctorj-pdf-1.5.0-alpha.7.jar!/gems/asciidoctor-pdf-1.5.0.alpha.7/lib/asciidoctor-pdf/converter.rb:1607)
        at RUBY.convert_document(/home/beltman/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.7/asciidoctorj-pdf-1.5.0-alpha.7.jar!/gems/asciidoctor-pdf-1.5.0.alpha.7/lib/asciidoctor-pdf/converter.rb:148)
        at RUBY.convert(/home/beltman/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.7/asciidoctorj-pdf-1.5.0-alpha.7.jar!/gems/asciidoctor-pdf-1.5.0.alpha.7/lib/asciidoctor-pdf/converter.rb:76)
        at RUBY.convert(/home/beltman/.m2/repository/org/asciidoctor/asciidoctorj/1.5.2/asciidoctorj-1.5.2.jar!/gems/asciidoctor-1.5.2/lib/asciidoctor/document.rb:1028)
        at RUBY.convert(/home/beltman/.m2/repository/org/asciidoctor/asciidoctorj/1.5.2/asciidoctorj-1.5.2.jar!/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1499)
        at RUBY.convert_file(/home/beltman/.m2/repository/org/asciidoctor/asciidoctorj/1.5.2/asciidoctorj-1.5.2.jar!/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1562)
        at RUBY.convertFile(<script>:68)
        at org.jruby.gen.InterfaceImpl1432220616.convertFile(org/jruby/gen/InterfaceImpl1432220616.gen:13)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

We run this build based on a transformed gdoc documentation site for Apache Wicket, located here: https://github.com/thijs1108/wicket/tree/asciidoc/wicket-user-guide

**Comment by abatalev** [comment]
possible solution - in pull request #225  small fix for simple docs without sections and doctitle

**Comment by dashorst** [comment]
It appears that a document without sections is causing this error. Unfortunately the error reporting doesn't provide a way to see which document was being processed, making it difficult to diagnose this error.

**Comment by mojavelinux** [comment]
I've confirmed this is the same issue. I'll merge the pull request shortly.

@dashorst The Asciidoctor Maven Plugin should be identifying which file it was on when it encountered a failed conversion. Could you file an issue in that repo?

**Comment by mojavelinux** [comment]
Note that this only happens when the `pagenums` attribute is enabled.

**Comment by mojavelinux** [comment]
I forgot that the `find_by` returns nil if no nodes are found. I'm sort of questioning that decision, but I vaguely remember why I did it. Either way, adding a nil check is the safest strategy.

**Comment by mojavelinux** [comment]
This was resolved by the following two commits:

* 0fdeab580db65f0352e0cec7e19dd9e033510716
* d77aba58348a5451a6afcf0d62d86c049c63680e

**Comment by mojavelinux** [comment]
The fix will be in alpha.9.
