### ISSUE TITLE
undefined method `+' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ponchofiesta** [asciidoctor/asciidoctor-pdf#2354]
By converting a new adoc document to PDF, I get an error message. Unfortunately the document itself is internal and I cannot share it. Is there a way to get the line of the adoc file, which causes the problem?

Using Asciidoctor-pdf 2.3

```
> asciidoctor-pdf -a pdf-themesdir=media -a pdf-theme=asciidoctor --trace .\en\XXX.adoc
C:/Users/XXX/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3908:in `block (3 levels) in ink_toc_level': undefined method `+' for nil:NilClass (NoMethodError)

                start_dots = last_fragment_pos.right + hanging_indent
                                                     ^
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn/document/bounding_box.rb:297:in `indent'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn/document.rb:528:in `indent'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3905:in `block (2 levels) in ink_toc_level'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:4509:in `block in theme_font'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn/font.rb:60:in `block in font'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn/font.rb:214:in `save_font'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn/font.rb:58:in `font'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/ext/prawn/extensions.rb:329:in `font'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:4507:in `theme_font'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3874:in `block in ink_toc_level'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3871:in `each'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3871:in `ink_toc_level'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3937:in `block (2 levels) in ink_toc_level'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn/document/bounding_box.rb:297:in `indent'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn/document.rb:528:in `indent'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3936:in `block in ink_toc_level'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3871:in `each'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3871:in `ink_toc_level'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3937:in `block (2 levels) in ink_toc_level'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn/document/bounding_box.rb:297:in `indent'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn/document.rb:528:in `indent'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3936:in `block in ink_toc_level'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3871:in `each'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3871:in `ink_toc_level'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:3857:in `ink_toc'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:309:in `block in convert_document'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:612:in `indent_section'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:200:in `convert_document'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/lib/asciidoctor/pdf/converter.rb:152:in `convert'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.17/lib/asciidoctor/document.rb:955:in `convert'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:118:in `convert'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:190:in `block in convert_file'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:190:in `open'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:190:in `convert_file'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.17/lib/asciidoctor/cli/invoker.rb:129:in `block in invoke!'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.17/lib/asciidoctor/cli/invoker.rb:112:in `each'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.17/lib/asciidoctor/cli/invoker.rb:112:in `invoke!'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/asciidoctor-pdf-2.3.0/bin/asciidoctor-pdf:46:in `<top (required)>'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/bin/asciidoctor-pdf:32:in `load'
        from C:/Users/AJHMF7Y/AppData/Local/Programs/rubyinstaller-3.1.2-1-x64/bin/asciidoctor-pdf:32:in `<main>'
```

**Comment by mojavelinux** [comment]
I'll need at least a reproducible example. I can't fix a scenario I can't
see.

**Comment by ponchofiesta** [comment]
That is understandable. I'll try to find a way next week.

**Comment by mojavelinux** [comment]
Also, please test with Asciidoctor PDF 2.3.2. You should always be using the latest patch release when filing an issue to be sure there are no old bugs in the picture.

**Comment by mojavelinux** [comment]
If it's too hard to reproduce the error, you can give me temporary access to a private repository. I'm willing to do that. What I'm not willing to do is guess.

**Comment by mojavelinux** [comment]
I discovered a reproducible test case. It may not be the way it is defined in your document, but I believe it emulates the problem.

```
= Document Title
:toc:

== Section 1

== foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo+++<span><br></span>+++
```

What's happening is that the last text fragment is not rendered. As a result, the position information is missing from the last fragment. And that causes the converter to crash. The converter needs to either handle this case, it track the position of every fragment so it can get the information it needs from the last fragment that was actually rendered.

**Comment by mojavelinux** [comment]
I'm going to try to port this to main, but it appears like main doesn't have the same problem...and in fact the behavior is different. So more research is needed ;)

**Comment by ponchofiesta** [comment]
@mojavelinux I've found the position in the document. I missed this position when I cleaned up the pandoc converted results. Looks like invalid Asciidoc. But I think it still shouldn't crash here. This is a very small test document causing exact my problem:

```
= User Manual
:toc: macro
:doctype: book

toc::[]

= *Calloff* +
abc
```

Removing bold sings ("*") or the "+" will cause asciidoctor-pdf not to crash. But both crashes.

**Comment by mojavelinux** [comment]
Thanks. That confirms what I suspected the problem was. I also realized
there were potentially a lot of other cases. So I made the code generally
robust.

By the way, using + at the end of a section title is nonsensical. A section
title must be a single line.

**Comment by mojavelinux** [comment]
Thanks to this bug report, I discovered a different regression in the main branch. I love when we get that kind of side effect. Just wanted to say thanks!

**Comment by ponchofiesta** [comment]
Thank you for your great work on this project!
