### ISSUE TITLE
Custom Title Page: extending the default page throws Name Error

### ISSUE THREAD

**Issue by DaelDe** [asciidoctor/asciidoctor-pdf#2369]
I need a custom title page to align the formatting to a company standard.

I followed the guide at https://docs.asciidoctor.org/pdf-converter/latest/extend/.

I am not so familiar with Ruby and Prawn. However, I wanted to modify the default title page. 
My idea was to use the ink_title_page method from https://github.com/asciidoctor/asciidoctor-pdf/blob/main/lib/asciidoctor/pdf/converter.rb#L3708. I copied it over to the `ExtendedPDFConverter` and called asciidoctor with it:
```
 asciidoctor-pdf -v -a compress  --trace -r ./pdf-converter/extended-pdf-converter.rb -r asciidoctor-lists -o main.pdf  "main.adoc"
```

in the output I get the following error:
```
pdf-converter/extended-pdf-converter.rb:10:in `ink_title_page': uninitialized constant ExtendedPDFConverter::AttributeList (NameError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-2.3.2/lib/asciidoctor/pdf/converter.rb:179:in `block in convert_document'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-2.3.2/lib/asciidoctor/pdf/ext/prawn/extensions.rb:1025:in `perform_on_single_page'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-2.3.2/lib/asciidoctor/pdf/converter.rb:179:in `convert_document'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-2.3.2/lib/asciidoctor/pdf/converter.rb:152:in `convert'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/document.rb:955:in `convert'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:118:in `convert'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:190:in `block in convert_file'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:190:in `open'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:190:in `convert_file'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/cli/invoker.rb:129:in `block in invoke!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/cli/invoker.rb:112:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/cli/invoker.rb:112:in `invoke!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-2.3.2/bin/asciidoctor-pdf:46:in `<top (required)>'
        from C:/Ruby30-x64/bin/asciidoctor-pdf:25:in `load'
        from C:/Ruby30-x64/bin/asciidoctor-pdf:25:in `<main>'
```

on line 10 of extended-pdf-converter.rb:
 ```
           logo_image_attrs = (AttributeList.new $2).parse %w(alt width height)
```

Was it the correct way to start with the default title page? How can I fix it.

Many Thanks

**Comment by mojavelinux** [comment]
You usually can't just copy code out of one converter and into another without some modification. In this case, since your class is not inside the Asciidoctor module, it cannot find AttributeList. You would need to replace it with ::Asciidoctor::AttributeList.

In the future, please direct usage questions to the project chat at https://chat.asciidoctor.org. Thanks!
