### ISSUE TITLE
asciidoctor-pdf just crashed after adding some text lines

### ISSUE THREAD

**Issue by eda1-fiunam** [asciidoctor/asciidoctor-pdf#2406]
Everything was ok while working on a document; then, after I added some lines, or after adding some new lines, I'm not sure exactly, the program just crashed.

After a lot of this kind of messages:

```
[Prawn::Icon - DEPRECATION WARNING]
  FontAwesome 4 icon was referenced as 'fa-lightbulb-o'.
  Use the FontAwesome 5 icon 'far-lightbulb' instead.
  This compatibility layer will be removed in Prawn::Icon 3.0.0.
```

the program just stopped working. But while compiling my doc inside Vim, this crashed too because of a dumped core.

Then in a terminal I added the --trace flag to the compiler instruction and I got this:

```
Traceback (most recent call last):
	12: from /usr/bin/asciidoctor-pdf:31:in `<main>'
	11: from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:111:in `invoke!'
	10: from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:111:in `each'
	 9: from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	 8: from /usr/lib/ruby/vendor_ruby/asciidoctor/convert.rb:183:in `convert_file'
	 7: from /usr/lib/ruby/vendor_ruby/asciidoctor/convert.rb:183:in `open'
	 6: from /usr/lib/ruby/vendor_ruby/asciidoctor/convert.rb:183:in `block in convert_file'
	 5: from /usr/lib/ruby/vendor_ruby/asciidoctor/convert.rb:118:in `convert'
	 4: from /usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:951:in `convert'
	 3: from /usr/lib/ruby/vendor_ruby/asciidoctor-pdf/converter.rb:118:in `convert'
	 2: from /usr/lib/ruby/vendor_ruby/asciidoctor-pdf/converter.rb:211:in `convert_document'
	 1: from /usr/lib/ruby/vendor_ruby/asciidoctor-pdf/prawn_ext/extensions.rb:682:in `delete_page'
/usr/lib/ruby/vendor_ruby/pdf/core/object_store.rb:96:in `object_id_for_page': undefined method `get_page_objects' for #<PDF::Core::ObjectStore:0x000055e49f161a78> (NoMethodError)

```

I'm using the Linux Mint ascii-doctor-pdf version that  it provides: PDF 1.5.0. I guess you aren't gonna help me, but a least I've let you know it.

Thank you anyway!

**Comment by eda1-fiunam** [comment]
I've isolated the problem. For this next text I get no problems (it's in spanish, but pay attention at the text structure):

```
[sidebar]
.Dobles apuntadores
--
Probablemente estés pensando que los dobles apuntadores, por ejemplo, `Reloj** this`, son una característica obscura y exótica del lenguaje C que tal vez nunca llegues a utilizar; sin embargo, es todo lo contrario: mucho del trabajo útil de este lenguaje en aplicaciones del mundo real se lleva a cabo _apuntando_ a variables apuntadoras.  El primer encuentro que tendrás con esta característica es cuando lleguemos al tema de _Listas enlazadas_: si programas éstas sin usar tipos abstractos, entonces estarás escribiendo argumentos de funciones como lo que acabas de ver; y si las programas con tipos abstractos, entonces el doble apuntador quedará, en cierto sentido, oculto. Sin embargo, siempre estarán ahí, de una forma u otra.  Es por esto que es imperativo que te quede claro su funcionamiento lo más pronto posible, porque no importa si el doble apuntador es explícito o implícito, tendrás que realizar dobles de-referencias.
--
```

And this text doesn't compile:

```
[sidebar]
.Dobles apuntadores
--
Probablemente estés pensando que los dobles apuntadores, por ejemplo, `Reloj** this`, son una característica obscura y exótica del lenguaje C que tal vez nunca llegues a utilizar; sin embargo, es todo lo contrario: mucho del trabajo útil de este lenguaje en aplicaciones del mundo real se lleva a cabo _apuntando_ a variables apuntadoras. 

El primer encuentro que tendrás con esta característica es cuando lleguemos al tema de _Listas enlazadas_: si programas éstas sin usar tipos abstractos, entonces estarás escribiendo argumentos de funciones como lo que acabas de ver; y si las programas con tipos abstractos, entonces el doble apuntador quedará, en cierto sentido, oculto. Sin embargo, siempre estarán ahí, de una forma u otra. 

Es por esto que es imperativo que te quede claro su funcionamiento lo más pronto posible, porque no importa si el doble apuntador es explícito o implícito, tendrás que realizar dobles de-referencias.
--
```

(Ironically this text is about double pointers in C, a source of crashes in C programs).

**Comment by mojavelinux** [comment]
As the issue template requested, please ask usage questions in the project chat at https://chat.asciidoctor.org. The issue tracker is for verified, triaged issues. This helps us to better maintain the project. Thanks!

> I'm using the Linux Mint ascii-doctor-pdf version that it provides: PDF 1.5.0. 

This version of Asciidoctor PDF is no longer supported. You should be using at least Asciidoctor PDF 2.3.

**Comment by eda1-fiunam** [comment]
I didn't mean to be a jerk, but it was a fact that I wasn't to receive any help 'cause I'm using an unsupported release, as this is the one that Linux Mint installs by default.

I love asciidoctor and from the bottom of my heart, thank you for this project.

**Comment by mojavelinux** [comment]
Thank you for appreciating our work! I hope to see you in the project chat!
