### ISSUE TITLE
Exception if asciidoc contains table of contents

### ISSUE THREAD

**Issue by may-bee** [asciidoctor/asciidoctor-pdf#27]
Hi,

if a asciidoc file contains a table of contents like
```
:toc:
toc::[]
```
generation ends with the following exception:
```
/.../asciidoctor-pdf/lib/asciidoctor/pdf_renderer.rb:1100:in `render_toc_node': undefined method `each' for nil:NilClass (NoMethodError)
	from /.../asciidoctor-pdf/lib/asciidoctor/pdf_renderer.rb:81:in `render_node'
	from /.../asciidoctor-pdf/lib/asciidoctor/pdf_renderer.rb:89:in `block in render_children'
	from /.../asciidoctor-pdf/lib/asciidoctor/pdf_renderer.rb:89:in `each'
	from /.../asciidoctor-pdf/lib/asciidoctor/pdf_renderer.rb:89:in `render_children'
	from /.../asciidoctor-pdf/lib/asciidoctor/pdf_renderer.rb:167:in `render_document_node'
	from /.../asciidoctor-pdf/lib/asciidoctor/pdf_renderer.rb:52:in `block in render'
	from /var/lib/gems/1.9.1/gems/prawn-1.0.0/lib/prawn/document.rb:228:in `instance_eval'
	from /var/lib/gems/1.9.1/gems/prawn-1.0.0/lib/prawn/document.rb:228:in `initialize'
	from /var/lib/gems/1.9.1/gems/prawn-1.0.0/lib/prawn/document.rb:144:in `new'
	from /var/lib/gems/1.9.1/gems/prawn-1.0.0/lib/prawn/document.rb:144:in `generate'
	from /.../asciidoctor-pdf/lib/asciidoctor/pdf_renderer.rb:46:in `render'
	from ../asciidoctor-pdf/bin/asciidoctor-pdf:68:in `<main>'
```

**Comment by mojavelinux** [comment]
This was resolved by https://github.com/asciidoctor/asciidoctor-pdf/commit/8b83f7681b2373e2dd9b8b5985f833b9533bb4ed.

**Comment by mojavelinux** [comment]
Note that we still need to implement manual placement for the toc. But for now, at least the processor doesn't crash if a toc macro is used. Instead, it inserts the toc in the predetermined location.
