### ISSUE TITLE
Where is output file

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor-pdf#30]
If I execute 
```
$ ./bin/asciidoctor-pdf  foo.ad
```
inside my install directory `/mylongpath/git/asciidoctor-pdf`, i find the output file `foo.pdf` in that directory.  On the other hand, if I execute it via
```
executeCommand("/mylongpath/git/asciidoctor-pdf", ["foo.ad"])
``` 
from within my MacOS program, I cannot find the output file.  Note that
```
executeCommand("/usr/bin/asciidoctor", ["foo.ad"])
``` 
does produce `foo.html` in the same directory as `foo.ad`.

Below is the log from the program.  Note that it would have been better to call `/usr/local/bin/asciidoctor-pdf`, but so far I can only install by cloning the repo and running `bundle` so as to install it in the cloned directory.

```
Recalled: documentURL => Optional("file:////Users/carlson/Dropbox/prog/Swift/adviewer/poetry/hib.ad")

LATEX: false
location: <WebScriptObject: 0x6080000193f0>
href: about:blank
executeCommand
Running: /Users/carlson/Dropbox/prog/git/asciidoctor-pdf/bin/asciidoctor-pdf
Args: [//Users/carlson/Dropbox/prog/Swift/adviewer/poetry/hib.ad]
/Library/Ruby/Gems/2.0.0/gems/tilt-2.0.1/lib/tilt/template.rb:83:in `initialize': /Users/carlson/Dropbox/prog/git/asciidoctor-pdf/bin/../data/templates/inline_quoted.html.slim is not valid US-ASCII (Encoding::InvalidByteSequenceError)
	from /Library/Ruby/Gems/2.0.0/gems/tilt-2.0.1/lib/tilt/mapping.rb:136:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/tilt-2.0.1/lib/tilt/mapping.rb:136:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/tilt-2.0.1/lib/tilt.rb:43:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor/converter/template.rb:268:in `block in scan_dir'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor/converter/template.rb:245:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor/converter/template.rb:245:in `scan_dir'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor/converter/template.rb:120:in `block in scan'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor/converter/template.rb:97:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor/converter/template.rb:97:in `scan'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor/converter/template.rb:77:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor/converter/factory.rb:219:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor/converter/factory.rb:219:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor/document.rb:985:in `create_converter'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor/document.rb:905:in `update_backend_attributes'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor/document.rb:379:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor.rb:1337:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor.rb:1337:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.0/lib/asciidoctor.rb:1355:in `load_file'
	from /Users/carlson/Dropbox/prog/git/asciidoctor-pdf/bin/asciidoctor-pdf:79:in `<main>'
Output: 
```

**Comment by mojavelinux** [comment]
I believe this is now resolved.
