### ISSUE TITLE
Exception Parsing Empty Table Attributes

### ISSUE THREAD

**Issue by devunwired** [asciidoctor/asciidoctor-pdf#314]
I came across something odd just now. I noticed that `asciidoctor-pdf` throws an exception when parsing a table with attributes defined that have no value:

````
[width="50%",cols="",options=""]
|===
|Testing | Can you hear me?
|===
````

Here is the stack trace:
```
$ asciidoctor-pdf sample.adoc --trace
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-pdf-1.5.0.alpha.9/lib/asciidoctor-pdf/converter.rb:1219:in `block in convert_table': undefined method `*' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-pdf-1.5.0.alpha.9/lib/asciidoctor-pdf/converter.rb:1219:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-pdf-1.5.0.alpha.9/lib/asciidoctor-pdf/converter.rb:1219:in `convert_table'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-pdf-1.5.0.alpha.9/lib/asciidoctor-pdf/converter.rb:97:in `convert'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-pdf-1.5.0.alpha.9/lib/asciidoctor-pdf/converter.rb:113:in `convert_content_for_block'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-pdf-1.5.0.alpha.9/lib/asciidoctor-pdf/converter.rb:320:in `convert_section'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-pdf-1.5.0.alpha.9/lib/asciidoctor-pdf/converter.rb:97:in `convert'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/document.rb:1086:in `content'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-pdf-1.5.0.alpha.9/lib/asciidoctor-pdf/converter.rb:113:in `convert_content_for_block'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-pdf-1.5.0.alpha.9/lib/asciidoctor-pdf/converter.rb:164:in `convert_document'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-pdf-1.5.0.alpha.9/lib/asciidoctor-pdf/converter.rb:97:in `convert'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/document.rb:1028:in `convert'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1499:in `convert'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-pdf-1.5.0.alpha.9/bin/asciidoctor-pdf:27:in `<top (required)>'
	from /usr/bin/asciidoctor-pdf:23:in `load'
	from /usr/bin/asciidoctor-pdf:23:in `<main>'
```

In the verions I have downloaded, line 1291 in `converter.rb` is this:

```ruby
column_widths = node.columns.map {|col| ((col.attr 'colpcwidth') * table_width) / 100.0 }
```

Admittedly, an attribute without a value shouldn't exist, so I just removed them and parsing works fine. However, it caught me off-guard because the HTML back end does not complain on this.

**Comment by mojavelinux** [comment]
This is probably an issue that needs to be addressed in core. We are checking whether the cols attribute exists, but not whether it is empty. In the HTML converter, it doesn't matter since we only pass through the value of colpcwidth. The probably here is that there is an attempt to multiply by it, so we end up with a multiplication error.

**Comment by mojavelinux** [comment]
But to clarify, I added a fix to the converter to be safe.
