### ISSUE TITLE
notitle document attribute throws exception

### ISSUE THREAD

**Issue by veeg** [asciidoctor/asciidoctor-pdf#365]
I'm attempting to render a document without a title page using the :notitle: document attribute
```
:notitle:
= Test
```

Results in the following trace
```
user@host:~> asciidoctor-pdf.ruby2.1 test.adoc --trace
/usr/lib64/ruby/gems/2.1.0/gems/prawn-2.0.2/lib/prawn/document.rb:668:in `generate_margin_box': undefined method `margins' for nil:NilClass (NoMethodError)
	from /usr/lib64/ruby/gems/2.1.0/gems/prawn-2.0.2/lib/prawn/document.rb:307:in `go_to_page'
	from /usr/lib64/ruby/gems/2.1.0/gems/asciidoctor-pdf-1.5.0.alpha.10/lib/asciidoctor-pdf/prawn_ext/extensions.rb:600:in `delete_page'
	from /usr/lib64/ruby/gems/2.1.0/gems/asciidoctor-pdf-1.5.0.alpha.10/lib/asciidoctor-pdf/converter.rb:168:in `convert_document'
	from /usr/lib64/ruby/gems/2.1.0/gems/asciidoctor-pdf-1.5.0.alpha.10/lib/asciidoctor-pdf/converter.rb:98:in `convert'
	from /usr/lib64/ruby/gems/2.1.0/gems/asciidoctor-1.5.3/lib/asciidoctor/document.rb:1044:in `convert'
	from /usr/lib64/ruby/gems/2.1.0/gems/asciidoctor-1.5.3/lib/asciidoctor.rb:1514:in `convert'
	from /usr/lib64/ruby/gems/2.1.0/gems/asciidoctor-1.5.3/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
	from /usr/lib64/ruby/gems/2.1.0/gems/asciidoctor-1.5.3/lib/asciidoctor/cli/invoker.rb:86:in `each'
	from /usr/lib64/ruby/gems/2.1.0/gems/asciidoctor-1.5.3/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
	from /usr/lib64/ruby/gems/2.1.0/gems/asciidoctor-pdf-1.5.0.alpha.10/bin/asciidoctor-pdf:27:in `<top (required)>'
	from /usr/bin/asciidoctor-pdf.ruby2.1:23:in `load'
	from /usr/bin/asciidoctor-pdf.ruby2.1:23:in `<main>'
```

Using the following version/environment
```
Asciidoctor PDF 1.5.0.alpha.10 using Asciidoctor 1.5.3 [http://asciidoctor.org]
Runtime Environment (ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by mojavelinux** [comment]
It's a known issue that Asciidoctor PDF fails if your document has no content (aside from the document title). Add any amount of content and it will work. This is the same as #317.
