### ISSUE TITLE
Cannot embed SVG Image plotted from GnuPlot

### ISSUE THREAD

**Issue by doedle** [asciidoctor/asciidoctor-pdf#407]
Cannot embed SVG-Image from Gnuplot. No  Problem with SVG-Images from other Editors (e.g. Inkscape).

```
└─ $ >>  asciidoctor-pdf --version
Asciidoctor PDF 1.5.0.alpha.11 using Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

```
└─ $ >>  asciidoctor-pdf --trace --verbose eval.adoc -o eval.pdf
asciidoctor: WARNING: could not embed image: <PATH>/clonewars.svg; undefined method 'strip' for nil:NilClass
~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ttfunk-1.4.0/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized
~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/prawn-2.0.2/lib/prawn/font/ttf.rb:117: warning: instance variable @italic_angle not initialized
```

```
└─ $ >> cat eval.adoc
[[abb_1, Abb. 1]]
.{blank} some titel
image::<PATH>clonewars.svg[scaledwidth=100%, align="center"]
```

It's urgent!

**Comment by mojavelinux** [comment]
I've put the file in a gist for easier downloading. (Please use this method in the future).

https://gist.github.com/mojavelinux/909b326fa0180f5157cd

**Comment by mojavelinux** [comment]
This is a bug/deficiency in prawn-svg. It does not recognize the color value "currentColor" (and fails trying to parse it). Please file an issue at https://github.com/mogest/prawn-svg and we will track its progress.

In the meantime, you can work around the problem by removing the "currentColor" from the SVG source, replacing it with a reasonable default. You might want to see if you can configure GnuPlot to not use this value.

**Comment by doedle** [comment]
thanks.

I get a stack trace too:
```
asciidoctor: WARNING: could not embed image: <PATH>/clonewars.svg; undefined method `strip' for nil:NilClass
~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/prawn-2.0.2/lib/prawn/document.rb:668:in `generate_margin_box': undefined method `margins' for nil:NilClass (NoMethodError)
        from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/prawn-2.0.2/lib/prawn/document.rb:307:in `go_to_page'
        from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/prawn_ext/extensions.rb:605:in `delete_page'
        from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:166:in `convert_document'
        from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96:in `convert'
        from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044:in `convert'
        from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503:in `convert'
        from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
        from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `each'
        from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
        from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-1.5.0.alpha.11/bin/asciidoctor-pdf:31:in `<top (required)>'
        from ~/.rbenv/versions/2.2.3/bin/asciidoctor-pdf:23:in `load'
        from ~/.rbenv/versions/2.2.3/bin/asciidoctor-pdf:23:in `<main>'

```

**Comment by mojavelinux** [comment]
This issue made me aware that we are swallowing the cause of errors in several places in the Asciidoctor PDF. That's why you can't get any more information about the source of the error.

Here's the real exception backtrace:

```
~/.rvm/gems/ruby-2.3.0@runtime/gems/prawn-svg-0.21.0/lib/prawn/svg/color.rb:161:in `color_to_hex': undefined method `strip' for nil:NilClass (NoMethodError)
	from ~/.rvm/gems/ruby-2.3.0@runtime/gems/prawn-svg-0.21.0/lib/prawn/svg/element.rb:158:in `block in parse_fill_and_stroke_attributes_and_call'
	from ~/.rvm/gems/ruby-2.3.0@runtime/gems/prawn-svg-0.21.0/lib/prawn/svg/element.rb:147:in `select'
	from ~/.rvm/gems/ruby-2.3.0@runtime/gems/prawn-svg-0.21.0/lib/prawn/svg/element.rb:147:in `parse_fill_and_stroke_attributes_and_call'
	from ~/.rvm/gems/ruby-2.3.0@runtime/gems/prawn-svg-0.21.0/lib/prawn/svg/element.rb:57:in `apply_styles'
	from ~/.rvm/gems/ruby-2.3.0@runtime/gems/prawn-svg-0.21.0/lib/prawn/svg/element.rb:13:in `initialize'
	from ~/.rvm/gems/ruby-2.3.0@runtime/gems/prawn-svg-0.21.0/lib/prawn/svg/element.rb:26:in `new'
	from ~/.rvm/gems/ruby-2.3.0@runtime/gems/prawn-svg-0.21.0/lib/prawn/svg/element.rb:26:in `block in each_child_element'
```

**Comment by doedle** [comment]
any workarounds except converting to bitmap?

**Comment by mojavelinux** [comment]
I've suggested the workaround already.

**Comment by doedle** [comment]
uh! ..just skipped by reading

**Comment by doedle** [comment]
it works for replacing "currentColor" with suitable value. 
Same issue for font-family "Arial".  Replacing with e.g. "sans" resolve the problem.

thank you very much!

**Comment by mojavelinux** [comment]
:+1: 

Can you file this in prawn-svg?

**Comment by mojavelinux** [comment]
Upstream issue: https://github.com/mogest/prawn-svg/issues/72

**Comment by mojavelinux** [comment]
Seems like this is already resolved upstream. We just need to upgrade.

**Comment by mojavelinux** [comment]
I can confirm that the upgrade to prawn-svg 0.22.1 fixes the issue.
