### ISSUE TITLE
Incompatibility with Rouge 2 source highlighter

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-pdf#471]
### Document

```
= Rouge highlighter
Guillaume Grossetie <ggrossetie@yuzutech.fr>
:source-highlighter: rouge

[source,javascript]
----
var test;
----
```

### Version

```
asciidoctor-pdf --version
Asciidoctor PDF 1.5.0.alpha.11 using Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

### Stack trace

Here's the full stack trace:

```
/home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/rouge_ext/formatters/prawn.rb:93:in `create_fragment': undefined method `fg' for {:fg=>"#888888"}:Hash (NoMethodError)
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/rouge_ext/formatters/prawn.rb:26:in `initialize'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:950:in `new'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:950:in `convert_listing_or_literal'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:112:in `convert_content_for_block'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:323:in `convert_section'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:112:in `convert_content_for_block'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:323:in `convert_section'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:112:in `convert_content_for_block'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:323:in `convert_section'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1104:in `content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:112:in `convert_content_for_block'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:163:in `convert_document'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/gems/asciidoctor-pdf-1.5.0.alpha.11/bin/asciidoctor-pdf:31:in `<top (required)>'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/bin/asciidoctor-pdf:23:in `load'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/bin/asciidoctor-pdf:23:in `<main>'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/bin/ruby_executable_hooks:15:in `eval'
	from /home/guillaume/.rvm/gems/ruby-2.3.0@intia/bin/ruby_executable_hooks:15:in `<main>'
```

NOTE: Everything is working fine with Coderay

**Comment by mojavelinux** [comment]
This is caused by an incompatibility with Rouge 2 (actually 1.11.1). They must have changed their API. Please use rouge 1.10.1 until we figure out how to fix this.

**Comment by Mogztter** [comment]
OK thanks for your quick reply. I think we should add a note on the README until we figure out how to fix this.

**Comment by mojavelinux** [comment]
It looks like our patch for https://github.com/jneen/rouge/issues/280 was breaking Rouge once it was fixed upstream. I added a version guard on the patch to ensure it only gets applied for older versions of Rouge.

**Comment by Mogztter** [comment]
Good thanks ;)
