### ISSUE TITLE
command line attribute pdf-fontsdir ignored

### ISSUE THREAD

**Issue by meisterluk** [asciidoctor/asciidoctor-pdf#543]
In the section documenting handling of custom fonts, it is pointed out that fontsdir needs to be set:

> When you execute Asciidoctor PDF, you need to specify the directory where the fonts reside using the pdf-fontsdir attribute:
>
> `$ asciidoctor-pdf -a pdf-style=basic-theme.yml -a pdf-fontsdir=path/to/fonts document.adoc`
>
> :warning:
> 	Currently, all fonts referenced by the theme need to be present in the directory specified by the pdf-fontsdir attribute. 

https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#custom-fonts

However, I think this value is completely ignored.

```
meisterluk@linux ~project % head -n 7 resources/theme/mybook-theme.yml
font:
  catalog:
    Andada:
      normal: Andada-Regular.ttf
      bold: Andada-Bold.ttf
      italic: Andada-Italic.ttf
      bold_italic: Andada-BoldItalic.ttf
meisterluk@linux ~project % ls resources/fonts/*.ttf
resources/fonts/Andada-BoldItalic.ttf  resources/fonts/Andada-Italic.ttf   resources/fonts/AndadaSC-BoldItalic.ttf  resources/fonts/AndadaSC-Italic.ttf
resources/fonts/Andada-Bold.ttf        resources/fonts/Andada-Regular.ttf  resources/fonts/AndadaSC-Bold.ttf        resources/fonts/AndadaSC-Regular.ttf
meisterluk@linux ~project % asciidoctor-pdf -n -d book -a pdf-stylesdir=resources/theme -a pdf-style=mybook -a pdf-fontsdir=resources/fonts --trace mybook.adoc
/var/lib/gems/2.3.0/gems/ttfunk-1.2.2/lib/ttfunk.rb:33:in `verify_and_open': /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.5/data/fonts/Andada-Regular.ttf not found (ArgumentError)
	from /var/lib/gems/2.3.0/gems/ttfunk-1.2.2/lib/ttfunk.rb:12:in `open'
	from /var/lib/gems/2.3.0/gems/prawn-1.2.1/lib/prawn/font/ttf.rb:347:in `read_ttf_file'
	from /var/lib/gems/2.3.0/gems/prawn-1.2.1/lib/prawn/font/ttf.rb:27:in `initialize'
	from /var/lib/gems/2.3.0/gems/prawn-1.2.1/lib/prawn/font.rb:292:in `new'
	from /var/lib/gems/2.3.0/gems/prawn-1.2.1/lib/prawn/font.rb:292:in `load'
	from /var/lib/gems/2.3.0/gems/prawn-1.2.1/lib/prawn/font.rb:244:in `find_font'
	from /var/lib/gems/2.3.0/gems/prawn-1.2.1/lib/prawn/font.rb:58:in `font'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.5/lib/asciidoctor-pdf/prawn_ext/extensions.rb:97:in `font'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.5/lib/asciidoctor-pdf/converter.rb:964:in `layout_title_page'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.5/lib/asciidoctor-pdf/converter.rb:104:in `convert_document'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.5/lib/asciidoctor-pdf/converter.rb:65:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `each'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.5/bin/asciidoctor-pdf:13:in `<top (required)>'
	from /usr/local/bin/asciidoctor-pdf:23:in `load'
	from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
```

Finally I was curious whether it actually looks up the font files and the answer is 'no':
```
meisterluk@linux ~project % strace asciidoctor-pdf -n -d book -a pdf-stylesdir=resources/theme -a pdf-style=osprojekte -a pdf-fontsdir=resources/fonts --trace osprojekte.adoc 2>&1 > /dev/null | grep fonts
execve("/usr/local/bin/asciidoctor-pdf", ["asciidoctor-pdf", "-n", "-d", "book", "-a", "pdf-stylesdir=resources/theme", "-a", "pdf-style=osprojekte", "-a", "pdf-fontsdir=resources/fonts", "--trace", "osprojekte.adoc"], [/* 89 vars */]) = 0
execve("/home/prokls/bin/ruby2.3", ["ruby2.3", "/usr/local/bin/asciidoctor-pdf", "-n", "-d", "book", "-a", "pdf-stylesdir=resources/theme", "-a", "pdf-style=osprojekte", "-a", "pdf-fontsdir=resources/fonts", "--trace", "osprojekte.adoc"], [/* 89 vars */]) = -1 ENOENT (No such file or directory)
execve("/usr/local/sbin/ruby2.3", ["ruby2.3", "/usr/local/bin/asciidoctor-pdf", "-n", "-d", "book", "-a", "pdf-stylesdir=resources/theme", "-a", "pdf-style=osprojekte", "-a", "pdf-fontsdir=resources/fonts", "--trace", "osprojekte.adoc"], [/* 89 vars */]) = -1 ENOENT (No such file or directory)
execve("/usr/local/bin/ruby2.3", ["ruby2.3", "/usr/local/bin/asciidoctor-pdf", "-n", "-d", "book", "-a", "pdf-stylesdir=resources/theme", "-a", "pdf-style=osprojekte", "-a", "pdf-fontsdir=resources/fonts", "--trace", "osprojekte.adoc"], [/* 89 vars */]) = -1 ENOENT (No such file or directory)
execve("/usr/sbin/ruby2.3", ["ruby2.3", "/usr/local/bin/asciidoctor-pdf", "-n", "-d", "book", "-a", "pdf-stylesdir=resources/theme", "-a", "pdf-style=osprojekte", "-a", "pdf-fontsdir=resources/fonts", "--trace", "osprojekte.adoc"], [/* 89 vars */]) = -1 ENOENT (No such file or directory)
execve("/usr/bin/ruby2.3", ["ruby2.3", "/usr/local/bin/asciidoctor-pdf", "-n", "-d", "book", "-a", "pdf-stylesdir=resources/theme", "-a", "pdf-style=osprojekte", "-a", "pdf-fontsdir=resources/fonts", "--trace", "osprojekte.adoc"], [/* 89 vars */]) = 0
stat("/usr/share/fonts/truetype", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.5/data/fonts/Andada-Regular.ttf", 0x7fff4daa85b0) = -1 ENOENT (No such file or directory)
write(2, "/var/lib/gems/2.3.0/gems/asciido"..., 94/var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.5/data/fonts/Andada-Regular.ttf not found) = 94
````

It directly uses the asciidoc-pdf's default font directory. Do I use it wrongfully?

_I need to point out:_ I know the workaround specifically using the absolute path in the YAML-file, but this is not acceptable for me.

**Comment by mojavelinux** [comment]
> asciidoctor-pdf-1.5.0.alpha.5

This is your problem. That version is waaaaay out of date. We're now at 1.5.0.alpha.12 (with 1.5.0.alpha.13) on the way. I have no idea what the state of themes are in 1.5.0.alpha.5, but that version certainly isn't supported.

I just tested your scenario against 1.5.0.alpha.12 and can confirm it works. However, I still recommend using absolute paths for the `pdf-stylesdir` and `pdf-fontsdir` attributes.

**Comment by meisterluk** [comment]
True, my Gemfile defined

```
gem 'asciidoctor-epub3', '1.0.0.alpha.2'
gem 'asciidoctor-pdf', '1.5.0.alpha.5'
```

release alpha 5. I now use

```
gem 'asciidoctor-pdf', '~> 1.5.0.alpha.12'
gem 'asciidoctor-epub3', '~> 1.5.0.alpha.6'
````

And it works :-) Thank you! :+1:

**Comment by mojavelinux** [comment]
Super!

Hopefully, you'll get to change that to alpha.13 later this week. Stay tuned, we're almost there!

**Comment by serussell** [comment]
Although, I'm seeing this as well with version 1.5.0.alpha.16:

```
➜  architecture asciidoctor-pdf --version
Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 1.5.7.1 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
➜  architecture asciidoctor-pdf -r asciidoctor-diagram -a pdf-stylesdir=./dot-asciidoctor/themes -a pdf-fontsdir=/usr/share/fonts/noto -a pdf-style=intlsos -o profile_issues-v0.pdf profile_issues.adoc                  
NotoSerif-Regular.ttf not found
  Use --trace for backtrace
➜  architecture ls -l /usr/share/fonts/noto/NotoSerif-Regular.ttf
-rw-r--r-- 1 root root 552144 Apr  4  2018 /usr/share/fonts/noto/NotoSerif-Regular.ttf
➜  architecture strace asciidoctor-pdf -r asciidoctor-diagram -a pdf-stylesdir=./dot-asciidoctor/themes -a pdf-fontsdir=/usr/share/fonts/noto -a pdf-style=intlsos -o profile_issues-v0.pdf profile_issues.adoc 2>&1 | grep fonts
execve("/home/ser/.gem/ruby/2.5.0/bin/asciidoctor-pdf", ["asciidoctor-pdf", "-r", "asciidoctor-diagram", "-a", "pdf-stylesdir=./dot-asciidoctor/"..., "-a", "pdf-fontsdir=/usr/share/fonts/no"..., "-a", "pdf-style=intlsos", "-o", "profile_issues-v0.pdf", "profile_issues.adoc"], 0x7ffd895c9988 /* 66 vars */) = 0
stat("/usr/share/fonts/truetype", 0x7ffcf201d1a0) = -1 ENOENT (No such file or directory)
```

What am _I_ doing wrong?

**Comment by mojavelinux** [comment]
I tried your scenario and it worked fine.

It seems to me like there is either an error in your theme file or the font is a symlink or something. I'm confused why you would get `/usr/share/fonts/truetype` when you never specify that directory anywhere. Or perhaps you do in your theme file.

It would be helpful if you shared your theme file.
