### ISSUE TITLE
Image errors should print the image name

### ISSUE THREAD

**Issue by guw** [asciidoctor/asciidoctor-pdf#587]
I'm working on converting a document to Asciidoc using a conversion tool. Troubleshooting image issues is extremely hard. Error messages are thrown at users without any hint what is causing the error. Even a `--verbose` option does not help.

When generating PDF output the error message `image file is an unrecognised format` gets printed. Unfortunately there is neither an indication about the problematic image nor the location in the document. Any would be really helpful in trouble shooting the image.

```
/usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/image_handler.rb:40:in `find': image file is an unrecognised format (Prawn::Errors::UnsupportedImageType)
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/images.rb:87:in `build_image_object'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb:72:in `block in arrange_images'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb:51:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb:51:in `arrange_images'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb:14:in `wrap'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:223:in `block (4 levels) in render'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:101:in `font_size'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/prawn_ext/extensions.rb:242:in `font_size'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:216:in `block (3 levels) in render'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pdf-core-0.6.1/lib/pdf/core/text.rb:182:in `text_rendering_mode'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:211:in `block (2 levels) in render'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pdf-core-0.6.1/lib/pdf/core/text.rb:204:in `character_spacing'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:210:in `block in render'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:207:in `save_font'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:209:in `render'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text.rb:376:in `fill_formatted_text_box'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text.rb:215:in `formatted_text'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text.rb:167:in `text'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:2257:in `typeset_text'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:1671:in `layout_prose'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:769:in `convert_content_for_list_item'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:632:in `block (2 levels) in convert_dlist'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/document/bounding_box.rb:286:in `indent'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/document.rb:486:in `indent'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:631:in `block in convert_dlist'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:622:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:622:in `convert_dlist'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96:in `convert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/list.rb:30:in `convert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:112:in `convert_content_for_block'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:323:in `convert_section'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96:in `convert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:112:in `convert_content_for_block'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:323:in `convert_section'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96:in `convert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:112:in `convert_content_for_block'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:323:in `convert_section'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96:in `convert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1104:in `content'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:112:in `convert_content_for_block'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:163:in `convert_document'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96:in `convert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044:in `convert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503:in `convert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/bin/asciidoctor:14:in `<top (required)>'
	from /usr/local/bin/asciidoctor:23:in `load'
	from /usr/local/bin/asciidoctor:23:in `<main>'
```

Another error exposing the same problem is `Prawn::Errors::CannotFit`.
```
/usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/line_wrap.rb:199:in `update_output_based_on_last_fragment': Prawn::Errors::CannotFit (Prawn::Errors::CannotFit)
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/line_wrap.rb:190:in `fragment_finished'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/line_wrap.rb:112:in `block in add_fragment_to_line'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/line_wrap.rb:96:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/line_wrap.rb:96:in `add_fragment_to_line'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/line_wrap.rb:81:in `block in apply_font_settings_and_add_fragment_to_line'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:245:in `block in apply_font_size'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:101:in `font_size'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/prawn_ext/extensions.rb:242:in `font_size'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:245:in `apply_font_size'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:167:in `block in apply_font_settings'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pdf-core-0.6.1/lib/pdf/core/text.rb:204:in `character_spacing'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:160:in `apply_font_settings'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/line_wrap.rb:77:in `apply_font_settings_and_add_fragment_to_line'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/line_wrap.rb:49:in `wrap_line'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/wrap.rb:53:in `wrap'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb:15:in `wrap'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:223:in `block (4 levels) in render'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:101:in `font_size'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/prawn_ext/extensions.rb:242:in `font_size'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:216:in `block (3 levels) in render'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pdf-core-0.6.1/lib/pdf/core/text.rb:182:in `text_rendering_mode'
	from /usr/local/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:211:in `block (2 levels) in render'

```

**Comment by mojavelinux** [comment]
Ah yes, we need to catch this exception like we do with block images and report the image that is being referenced.

**Comment by mojavelinux** [comment]
Keep in mind that right now, only png and jpg images are supported. In alpha.14 it will be possible to also use just about any image type if prawn-gmagick is installed.

**Comment by mojavelinux** [comment]
The CannotFit errors are low-level bugs that simply need to be fixed. I believe the source of the problem is related to #447.
