### ISSUE TITLE
could not embed image, nil can't be coerced into Float

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-pdf#738]
### Output
```
asciidoctor-pdf elastic.adoc --trace                      
asciidoctor: WARNING: could not embed image: /home/guillaume/elastic.svg; nil can't be coerced into Float
```

### Version
```
asciidoctor-pdf -v                                            
```
```
Asciidoctor PDF 1.5.0.alpha.13 using Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```
```
ruby -v
```
```
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```
### Gem
```
gem list
```
```
*** LOCAL GEMS ***

addressable (2.4.0)
afm (0.2.2)
Ascii85 (1.0.2)
asciidoctor (1.5.4)
asciidoctor-pdf (1.5.0.alpha.13, 1.5.0.alpha.12, 1.5.0.alpha.11)
bigdecimal (1.2.8)
bundler-unload (1.0.2)
coderay (1.1.1)
css_parser (1.4.2)
did_you_mean (1.0.0)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
hashery (2.1.2)
io-console (0.4.5)
json (1.8.3)
minitest (5.8.3)
net-telnet (0.1.1)
pdf-core (0.6.1)
pdf-reader (1.4.0)
polyglot (0.3.5)
power_assert (0.2.6)
prawn (2.1.0)
prawn-icon (1.2.0, 1.1.0, 1.0.0)
prawn-svg (0.25.1, 0.21.0)
prawn-table (0.2.2)
prawn-templates (0.0.3)
psych (2.0.17)
rake (10.4.2)
rdoc (4.2.1)
rouge (2.0.1)
ruby-rc4 (0.1.5)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
safe_yaml (1.0.4)
test-unit (3.1.5)
thread_safe (0.3.5)
treetop (1.5.3)
ttfunk (1.4.0)
```

Is this error related to my svg file ? If so how can I fix my svg ?

**Comment by Mogztter** [comment]
If I modify my document to use an inline image I get a full stack trace:

```
/home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/path.rb:73:in `+': nil can't be coerced into Float (TypeError)
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/path.rb:73:in `parse_path_command'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/path.rb:30:in `block in parse'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/path.rb:25:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/path.rb:25:in `parse'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:48:in `parse_and_apply'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:43:in `process'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:129:in `block in process_child_elements'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `block in each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:124:in `process_child_elements'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:53:in `parse_and_apply'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:43:in `process'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:129:in `block in process_child_elements'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `block in each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:124:in `process_child_elements'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:53:in `parse_and_apply'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:43:in `process'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:129:in `block in process_child_elements'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `block in each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:124:in `process_child_elements'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:53:in `parse_and_apply'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:43:in `process'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:129:in `block in process_child_elements'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `block in each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:124:in `process_child_elements'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:53:in `parse_and_apply'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:43:in `process'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/interface.rb:48:in `block (2 levels) in draw'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/pdf-core-0.6.1/lib/pdf/core/renderer.rb:236:in `save_graphics_state'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/document/internals.rb:31:in `save_graphics_state'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/interface.rb:43:in `block in draw'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/document/bounding_box.rb:198:in `init_bounding_box'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/document/bounding_box.rb:159:in `bounding_box'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/interface.rb:42:in `draw'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/formatted_text/inline_image_renderer.rb:32:in `block in render_behind'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/document.rb:346:in `float'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/formatted_text/inline_image_renderer.rb:32:in `render_behind'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:558:in `block in draw_fragment_underlays'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:557:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:557:in `draw_fragment_underlays'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:277:in `draw_fragment'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/wrap.rb:148:in `block in format_and_draw_fragment'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:245:in `block in apply_font_size'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:101:in `font_size'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/prawn_ext/extensions.rb:282:in `font_size'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:245:in `apply_font_size'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:167:in `block in apply_font_settings'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/pdf-core-0.6.1/lib/pdf/core/text.rb:204:in `character_spacing'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:160:in `apply_font_settings'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:136:in `apply_color_and_font_settings'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/wrap.rb:147:in `format_and_draw_fragment'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/wrap.rb:95:in `block in print_line'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/wrap.rb:93:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/wrap.rb:93:in `print_line'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/wrap.rb:61:in `wrap'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb:15:in `wrap'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:223:in `block (4 levels) in render'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:101:in `font_size'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/prawn_ext/extensions.rb:282:in `font_size'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:216:in `block (3 levels) in render'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/pdf-core-0.6.1/lib/pdf/core/text.rb:182:in `text_rendering_mode'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:211:in `block (2 levels) in render'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/pdf-core-0.6.1/lib/pdf/core/text.rb:204:in `character_spacing'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:210:in `block in render'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:207:in `save_font'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:209:in `render'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text.rb:376:in `fill_formatted_text_box'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text.rb:215:in `formatted_text'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text.rb:167:in `text'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:2483:in `typeset_text'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:1845:in `layout_prose'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:440:in `convert_paragraph'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:103:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:119:in `convert_content_for_block'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:358:in `convert_section'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:103:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1104:in `content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:119:in `convert_content_for_block'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:177:in `convert_document'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:103:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/bin/asciidoctor-pdf:31:in `<top (required)>'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/bin/asciidoctor-pdf:23:in `load'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/bin/asciidoctor-pdf:23:in `<main>'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mojavelinux** [comment]
Could you share the SVG?

It appears that there is a lineto directive (L) that is missing a y coordinate. prawn-svg assume a value is provided, hence the nil exception. I'd say it's probably an invalid SVG.

Many tools produce broken SVGs (which is usually hard to detect because it requires validating all of the shapes). Yet, as always, browsers are extremely forgiving. You may be encountering that situation.

**Comment by mojavelinux** [comment]
I always recommend running your SVG through a tool like svgo. You don't necessarily need to enable a ton of optimizations. But it does fix a lot of problems. (Always check the result, though, because in some cases it may have side effects).

**Comment by Mogztter** [comment]
> Could you share the SVG?

Sure, here it is: https://drive.google.com/open?id=0B1rPjnFlfglqaEQzeFd2am84ME0

> It appears that there is a lineto directive (L) that is missing a y coordinate. prawn-svg assumes a value is provided, hence the nil exception. I'd say it's probably an invalid SVG.

I did try to find the "lineto" directive but it's quite hard 😞 

> I always recommend running your SVG through a tool like svgo. You don't necessarily need to enable a ton of optimizations. But it does fix a lot of problems. (Always check the result, though, because in some cases it may have side effects).

Thanks I will try

**Comment by mojavelinux** [comment]
I was able to confirm that running svgo with default settings fixes the image. I recommend taking this image to prawn-svg so that Roger can investigate and decide if the original image should be able to be read.

**Comment by mojavelinux** [comment]
Let's mark this as being fixed in alpha.14, which includes the prawn-svg upgrade.

**Comment by Mogztter** [comment]
Thanks!
