### ISSUE TITLE
crash on running the binary

### ISSUE THREAD

**Issue by aurabindo** [asciidoctor/asciidoctor-pdf#779]
I just installed the prelease asciidoctor-pdf 
asciidoctor-pdf -v crashes with:

```
/home/aj/.rvm/gems/ruby-2.3.3/gems/prawn-templates-0.0.3/lib/prawn/templates.rb:246:in `<top (required)>': can't modify frozen Array (RuntimeError)
	from /home/aj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/aj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-pdf-1.5.0.alpha.14/lib/asciidoctor-pdf/converter.rb:10:in `<top (required)>'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-pdf-1.5.0.alpha.14/lib/asciidoctor-pdf.rb:3:in `require_relative'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-pdf-1.5.0.alpha.14/lib/asciidoctor-pdf.rb:3:in `<top (required)>'
	from /home/aj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/aj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-pdf-1.5.0.alpha.14/bin/asciidoctor-pdf:4:in `<top (required)>'
	from /home/aj/.rvm/gems/ruby-2.3.3/bin/asciidoctor-pdf:22:in `load'
	from /home/aj/.rvm/gems/ruby-2.3.3/bin/asciidoctor-pdf:22:in `<main>'
	from /home/aj/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/aj/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```
Kindly advice how I can fix this

**Comment by veeg** [comment]
Issue #775 covers this exact problem.

**Comment by mojavelinux** [comment]
I'm starting work on the next release now that prawn-templates has been updated.
