### ISSUE TITLE
Exception when processing progit book

### ISSUE THREAD

**Issue by jnavila** [asciidoctor/asciidoctor-pdf#859]
Trying to use the latest tag on the progit book (https://github.com/progit/progit2), there is a crash

``` bash
$ bundle exec asciidoctor-pdf -b pdf --verbose --trace progit.asc
/home/user/.gems/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:191:in `convert_document': undefined method `sections?' for #<Asciidoctor::Document:0x00000002261450> (NoMethodError)
Did you mean?  sections
        from /home/user/.gems/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:118:in `convert'
        from /home/user/.gems/gems/asciidoctor-1.5.0/lib/asciidoctor/document.rb:1010:in `convert'
        from /home/user/.gems/gems/asciidoctor-1.5.0/lib/asciidoctor.rb:1459:in `convert'
        from /home/user/.gems/gems/asciidoctor-1.5.0/lib/asciidoctor/cli/invoker.rb:93:in `block in invoke!'
        from /home/user/.gems/gems/asciidoctor-1.5.0/lib/asciidoctor/cli/invoker.rb:85:in `each'
        from /home/user/.gems/gems/asciidoctor-1.5.0/lib/asciidoctor/cli/invoker.rb:85:in `invoke!'
        from /home/user/.gems/gems/asciidoctor-pdf-1.5.0.alpha.16/bin/asciidoctor-pdf:31:in `<top (required)>'
        from /home/user/.gems/bin/asciidoctor-pdf:23:in `load'
        from /home/user/.gems/bin/asciidoctor-pdf:23:in `<main>'
```

**Comment by jnavila** [comment]
Forget it. Upgrading asciidoctor gem as well...
