### ISSUE TITLE
asciidoctor-pdf fails to process a menu macro inside a section title

### ISSUE THREAD

**Issue by tiagoma** [asciidoctor/asciidoctor-pdf#934]
The following code is processed and styled correctly in asciidoctor with HTML5 output, but asciidoctor-pdf fails to process it:

```
:experimental:
== menu:File[Open]
```

I get the following traceback:

```
Traceback (most recent call last):
	26: from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
	25: from /usr/local/bin/asciidoctor-pdf:23:in `load'
	24: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.16/bin/asciidoctor-pdf:31:in `<top (required)>'
	23: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:112:in `invoke!'
	22: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:112:in `each'
	21: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:129:in `block in invoke!'
	20: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `convert_file'
	19: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `open'
	18: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `block in convert_file'
	17: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1473:in `convert'
	16: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1361:in `load'
	15: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/document.rb:565:in `parse'
	14: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/parser.rb:96:in `parse'
	13: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/parser.rb:328:in `next_section'
	12: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/parser.rb:290:in `next_section'
	11: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/parser.rb:1605:in `initialize_section'
	10: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:299:in `title'
	 9: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/substitutors.rb:150:in `apply_title_subs'
	 8: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/substitutors.rb:106:in `apply_subs'
	 7: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/substitutors.rb:106:in `each'
	 6: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/substitutors.rb:117:in `block in apply_subs'
	 5: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/substitutors.rb:574:in `sub_macros'
	 4: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/substitutors.rb:574:in `gsub'
	 3: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/substitutors.rb:596:in `block in sub_macros'
	 2: from /var/lib/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/inline.rb:39:in `convert'
	 1: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:118:in `convert'
/var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:2019:in `convert_inline_menu': asciidoctor: FAILED: /home/tiagoma/menu.adoc: Failed to load AsciiDoc document - undefined method `menu_caret_content' for nil:NilClass (NoMethodError)
```
This could be related to #313, which is in progress.

**Comment by jcayouette** [comment]
Confirmed, I have the same issue.

**Comment by mojavelinux** [comment]
The problem here is that the text of a section or block title is converted before the convert phase. As a result, the PDF theme has not been loaded, so we get a nil object exception. I fixed this by loading the theme lazily so it's available when the processor invokes the method to convert the menu.

**Comment by mojavelinux** [comment]
This problem is not related to #313.
