### ISSUE TITLE
Use of transparent in table_border_color

### ISSUE THREAD

**Issue by 1marc1** [asciidoctor/asciidoctor-pdf#990]
This is a very low priority issue, but I thought it is still worth mentioning.

If I have the following in my PDF theme:

```
table:
  border_color: transparent
```

Then, upon creation of my PDF document, I get the following error:

```
/var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/graphics/color.rb:100:in `color_type': Unknown type of color: "transparent" (ArgumentError)
	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/graphics/color.rb:130:in `color_space'
	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/graphics/color.rb:178:in `set_color'
	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/graphics/color.rb:189:in `set_stroke_color'
	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/graphics/color.rb:52:in `stroke_color'
	from /var/lib/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:766:in `block (2 levels) in draw_borders'
	from /var/lib/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:730:in `each'
	from /var/lib/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:730:in `block in draw_borders'
	from /var/lib/gems/2.3.0/gems/prawn-2.2.2/lib/prawn/document.rb:650:in `mask'
	from /var/lib/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:729:in `draw_borders'
	from /var/lib/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:418:in `block in draw_cells'
	from /var/lib/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:417:in `each'
	from /var/lib/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:417:in `draw_cells'
	from /var/lib/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:425:in `ink_and_draw_cells'
	from /var/lib/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:312:in `block in draw'
	from /var/lib/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:680:in `with_position'
	from /var/lib/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:260:in `draw'
	from /var/lib/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table.rb:112:in `table'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:1748:in `convert_table'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:118:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.6.2/lib/asciidoctor/abstract_block.rb:70:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.6.2/lib/asciidoctor/abstract_block.rb:79:in `block in content'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.6.2/lib/asciidoctor/abstract_block.rb:79:in `map'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.6.2/lib/asciidoctor/abstract_block.rb:79:in `content'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.6.2/lib/asciidoctor/document.rb:1118:in `content'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:134:in `convert_content_for_block'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:211:in `convert_document'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:118:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.6.2/lib/asciidoctor/document.rb:1058:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.6.2/lib/asciidoctor.rb:1502:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.6.2/lib/asciidoctor.rb:1575:in `block in convert_file'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.6.2/lib/asciidoctor.rb:1575:in `open'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.6.2/lib/asciidoctor.rb:1575:in `convert_file'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.6.2/lib/asciidoctor/cli/invoker.rb:108:in `block in invoke!'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.6.2/lib/asciidoctor/cli/invoker.rb:102:in `each'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.6.2/lib/asciidoctor/cli/invoker.rb:102:in `invoke!'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.16/bin/asciidoctor-pdf:31:in `<top (required)>'
	from /usr/local/bin/asciidoctor-pdf:23:in `load'
	from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
```

**Comment by mojavelinux** [comment]
I believe this problem has already been resolved in the master branch. Can you verify?

See https://github.com/asciidoctor/asciidoctor-pdf#development

**Comment by mojavelinux** [comment]
You're right. It turns out that this border handling happens in a separate module, prawn-table. Really, this needs to be moved upstream so that prawn-table provides some way to set the opacity. I've submitted a PR to monkeypatch prawn-table to add this support. See https://github.com/asciidoctor/asciidoctor-pdf/pull/992.
